### ISSUE TITLE
[Routing] RESTFull using routing prefix method PUT

### ISSUE THREAD

**Issue by afranioce** [FriendsOfSymfony/FOSRestBundle#1010]
I am using symfony version 2.6.6
```yaml
#src/Acme/Resources/config/routing.yml
acme_rest_api_profile:
    resource: "@Acme/Resources/config/routing/profile.yml"
    prefix:   /api/user/profile
```
Routing to profile, i'm taking the user by the session and does not need to pass the parameter.
```yaml
acme_rest_api_profile_show:
    path: /
    defaults: { _controller: RestAPIBundle:Profile:show, _format: ~ }
    requirements:
        _method: GET
acme_rest_api_profile_update:
    path: /
    defaults: { _controller: RestAPIBundle:Profile:edit, _format: ~ }
    requirements:
        _method: PUT
```
http://test.local/api/user/profile "No route found for "PUT /api/user/profile"
http://test.local/api/user/profile/ "Return success"

What am I doing something wrong?
