### ISSUE TITLE
Wrong content-type for svg images

### ISSUE THREAD

**Issue by mpbzh** [FriendsOfSymfony/FOSRestBundle#1012]
I have the following configuration for my RestBundle:
```yaml
# app/config/config.yml
fos_rest:
    param_fetcher_listener: true
    routing_loader:
        default_format: json
    view:
        view_response_listener: 'force'
        formats:
            xml:  true
            json: true
    allowed_methods_listener: true
    access_denied_listener:
        json: true

    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, }
            - { path: '^/', priorities: [ '*/*' ], prefer_extension: true }
```

The idea is, that the RestBundle should only be responsible for `/api` routes and everything else should be ignored by it.

It seems that svg images get the wrong content-type when accessed through the controller.
In `prod`, an svg image which is directly accessed is returned with a content-type `image/svg+xml`. 

However in `dev`, when the image is served by the controller, it is returned with the content type `text/html`, which causes the browser to ignore the image (It is displayed like a non-existing image) and according to the Chrome debugger it is returned with a `406 (Not Acceptable)`.
