### ISSUE TITLE
Validation doesn't work for GET requests

### ISSUE THREAD

**Issue by maZahaca** [FriendsOfSymfony/FOSRestBundle#1022]
I have configuration:
```yml
fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
```
Validation doesn't work for GET requests:
FOS\RestBundle\Request\AbstractRequestBodyParamConverter::execute
```php
$object = $this->serializer->deserialize(
                $request->getContent(),
                $configuration->getClass(),
                $request->getContentType(),
                $context
);
```
because $request->getContent() does not contain get query values.
