### ISSUE TITLE
Validation doesn't work when used custom ParamConverter

### ISSUE THREAD

**Issue by maZahaca** [FriendsOfSymfony/FOSRestBundle#1023]
I have configuration: 
```yml
fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
```
I used validation as it's described in http://symfony.com/doc/current/bundles/FOSRestBundle/3-listener-support.html#validation
But instead of fos_rest.request_body converter I used my_converter (some custom converter with priority=-2).
In fact my converter was executed successfully, but then code tries to execute RequestBodyParamConverter::execute for second parameter (ConstraintViolationListInterface $validationErrors) and fails.
