### ISSUE TITLE
Error validating param_fetcher_listener configuration parameter

### ISSUE THREAD

**Issue by numesmat** [FriendsOfSymfony/FOSRestBundle#1037]
FOSRestBundle version: 1.6.0-RC1

I have the following configuration ...
```yaml
fos_rest:
    param_fetcher_listener: true
    ...
```
... and getting the following error:
```
[InvalidArgumentException]                                                                                                     
  The param_fetcher_listener option does not support {"enabled":true,"service":null}. Please choose one of [false,true,"force"]
```
