### ISSUE TITLE
Custom path for routes in annotations

### ISSUE THREAD

**Issue by ivaaaan** [FriendsOfSymfony/FOSRestBundle#1071]
Ok, i'm having a action in my controller:

```php
    public function getUserBooksAction(User $user)
    {

    }
```

```bash
$ php app/console routes:debug | grep books

 get_books_user                           GET      ANY    ANY  /api/books/{user}/user.{_format}                   

```

wtf? why `/user.{_format`. how i can fix this?

My config:

```yaml
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: false
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json
```

And api routing:
```
book:
  type: rest
  resource: ApiBundle\Controller\BooksController
```
