### ISSUE TITLE
Disable CSRF on a "context" basis

### ISSUE THREAD

**Issue by jbenezech** [FriendsOfSymfony/FOSRestBundle#1121]
We'd like to use the same controllers/forms for both our web client interface and our REST api that serves mobile apps.
Application users may be using the mobile app or the web client and authenticate with the same credentials.
I understand we can disable CSRF protection on a per-user basis, assigning a specific role, but this doesn't seem to suit our scenario.

Would it be possible to extend this functionality to a per-context basis, maybe using request headers ? Is there today a workaround for that ?

**Comment by lsmith77** [comment]
maybe in 2.0 as part of https://github.com/FriendsOfSymfony/FOSRestBundle/pull/955

**Comment by alfonsomga** [comment]
Hey @jbenezech that scenario looks insteresting, you solved it?

**Comment by jbenezech** [comment]
@alfonsomga , as a temporary solution, we've solved that by registering a form type extension which disables the csrf protection based on the request path (/api)

**Comment by Ma27** [comment]
I'd add a new configuration parameter that disables the extension if the headers are not correct:

``` yaml
fos_rest:
    disable_csrf:
        role: ROLE_API (defaultNull)
        headers:
            Accept:
                - text/html (can be string or array if many types should be accepted)
```

if you'd be fine with that approach, I'd work on it when having time :)

/cc @lsmith77 @Ener-Getick
