### ISSUE TITLE
Fatal error: Class 'Metadata\Driver\LazyLoadingDriver' not found

### ISSUE THREAD

**Issue by HelloGrayson** [FriendsOfSymfony/FOSRestBundle#119]
For some reason getting this... Using Symfony 2.0.1. Up to date with current FOSRestBundle.

_config.yml_

``` yaml
fos_rest:
    view:
        formats:
            json: true
            rss: false
            xml: false
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
```

_controller_

``` php
        $view = View::create();
        $view->setData(array('test'));
        return $view;
```

Causes the following error: `Fatal error: Class 'Metadata\Driver\LazyLoadingDriver' not found in project/app/cache/dev/appDevDebugProjectContainer.php on line 1708`

That file doesn't seem to exist... Closest thing I can find is `JMS\SerializerBundle\Serializer\LazyLoadingSerializer`
