### ISSUE TITLE
add a custom expression language based function for the routing

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/FOSRestBundle#1202]
see https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1183/files#r44323889

**Comment by Ener-Getick** [comment]
I suppose we can always use composer/semver as this package is installed by default.

I'd like something like:
```yaml
route:
    # ...
    condition: matchVersion('^1.0|^2.0')
```
