### ISSUE TITLE
Behavior change in format listener configuration

### ISSUE THREAD

**Issue by aledeg** [FriendsOfSymfony/FOSRestBundle#1205]
I updated the bundle recently and I found a discrepancy in the behavior of my API.

Here is my configuration:
```yaml
fos_rest:
    routing_loader:
        include_format: false
    view:
        formats:
            json: ~
            xml: ~
        view_response_listener: force
    format_listener:
        rules:
          - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
          - { path: '^/', stop: true }
```
Before the update, I received JSON response when I asked for JSON (```"Accept: application/json"```) and I received XML response when I asked for XML (```"Accept: application/xml"```).
After the update, I received JSON response no matter what I asked for.

Basically, it was because when I asked for XML, I got the fallback instead. I figured that the problem was with the mime-type extraction process and I changed my configuration to the following:
```yaml
fos_rest:
    routing_loader:
        include_format: false
    view:
        formats:
            json: ~
            xml: ~
        view_response_listener: force
    format_listener:
        rules:
          - { path: '^/api', priorities: ['json', 'xml', 'application/xml'], fallback_format: json, prefer_extension: false }
          - { path: '^/', stop: true }
```
I found that the mime-type for XML was transformed to ```text/xml``` thus not matching the value in my header (```application/xml```).

My actual commit is 82b8388975e272fb6d1748262d02c553a9b0ca4d.
My previous commit was 9fe38af32a22cb033d0499bc2ab613a22fce8156

Is that behavior normal? Is this a bug?

**Comment by Ener-Getick** [comment]
Yes, this is the expected behavior (see https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/UPGRADING.md). 

Unfortunately, we can't get all the mime types corresponding to a format... (https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Negotiation/FormatNegotiator.php#L68) 

You can find an explanation here: https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1149#discussion_r41261839

**Comment by aledeg** [comment]
I blame it on my eyes. I was reading https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/UPGRADING.md earlier and I didn't find the answer. With a thorough reading, I found that it is detailed but only for the ```view```.

Thank you for your answer.

Should I leave this open?

**Comment by Ener-Getick** [comment]
Except if you think that we should improve something, you can close this.

**Comment by aledeg** [comment]
Maybe adding that it can be fixed also with the ```priorities```.
I made a test with the mime-type in the view section and I have the expected result.

**Comment by lsmith77** [comment]
what do you mean "fixed also with the priorities"?

**Comment by aledeg** [comment]
I mean that to fix my original issue, I could do either
```yaml
# This is with the mime-type configuration
fos_rest:
    routing_loader:
        include_format: false
    view:
        formats:
            json: ~
            xml: ~
        view_response_listener: force
        mime_types:
            xml: [application/xml]
    format_listener:
        rules:
          - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
          - { path: '^/', stop: true }
```
or 
```yaml
# This is with the priorities configuration
fos_rest:
    routing_loader:
        include_format: false
    view:
        formats:
            json: ~
            xml: ~
        view_response_listener: force
    format_listener:
        rules:
          - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
          - { path: '^/', stop: true }
```
