### ISSUE TITLE
unsupported "name_prefix"

### ISSUE THREAD

**Issue by cacahouete78** [FriendsOfSymfony/FOSRestBundle#1210]
Hello,

When I try to use name_prefix in my routing.yml

````
amc_app_users_api:
    resource: '@AmcAppBundle/Controller/API/UsersController.php'
    type: rest
    prefix: /api/users
    name_prefix: app_users_api_
````

I have the following issue :

````
[InvalidArgumentException]
The routing file "H:\Projects\test\src\Amc\AppBundle/Resources/config/routing.yml" contains unsupported keys for "amc_app_users_api": "name_prefix". Expected one of: "resource", "type", "prefix", "pattern", "path", "host", "schemes", "methods", "defaults", "requirements","options", "condition".  
````

I can use the annotation @NamePrefix in my controller to solve temporarily the probleme, but I would like to know if name_prefix in routing file is juste a bug or deprecated or deleted parameter ?

(I use SF2.7)

**Comment by Ener-Getick** [comment]
This is not supported in a routing  file managed by symfony. 

If you want to use this, you have to create a dedicated file for your rest routes and to load it:
```yaml
fos_rest:
    resource: fos_rest.yml
    type: rest
```
