### ISSUE TITLE
Implementing a custom encoder

### ISSUE THREAD

**Issue by PalliDotCom** [FriendsOfSymfony/FOSRestBundle#1239]
Is it possible to implement a custom encoder. I want to implement a encoder for the bson format.
http://bsonspec.org/

I´ve implemented a custom DecoderInterface and added this to the configuration:

```
fos_rest:
    body_listener:
        decoders:
             bson: bson_decoder
```

But the request still fails:

> No route found for "PUT /api/test.bson" 

Any ideas?

**Comment by Ener-Getick** [comment]
Not sure what you mean.

Do you have this in your config ?
```yml
fos_rest:
    routing_loader:
        include_format: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/', priorities: ['bson', 'json'], fallback_format: json, prefer_extension: true }
```

Then if you want to use bson you should create a new [encoder](http://api.symfony.com/2.4/Symfony/Component/Serializer/Encoder/EncoderInterface.html) and tag it with ``serializer.encoder`` (if you use the symfony serializer).
Or if you use the jms serializer, you have to create a new ``SerializationVisitor`` and tag it with ``jms_serializer.serialization_visitor``.

Then normally you will have the possibility to use bson.
