### ISSUE TITLE
FOSUser model properties not show

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfSymfony/FOSRestBundle#1274]
With those two serializer configurations:

```yaml
FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [list, details]
        username:
            expose: true
            groups: [details]
        email:
            expose: true
            groups: [details]

AppBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        firstname:
            expose: true
            groups: [list, details]
        lastname:
            expose: true
            groups: [list, details]
        locale:
            expose: true
            groups: [details]
```

I don't have parent class properties since upgrading from `v1.7.4` to `v1.7.6`:

```bash
$ curl -H "Authorization: Bearer 15ea658" http://localhost:8000/api/user
{"id":1,"firstname":"John","lastname":"Doe","locale":"fr"}
```
