### ISSUE TITLE
"Yaml routing loader does not support given key: "name_prefix". Expected one of the (type, resource, prefix, pattern, options, defaults, requirements)."

### ISSUE THREAD

**Issue by ericclemmons** [FriendsOfSymfony/FOSRestBundle#129]
I've been able to successfully use the bundle with my application for some time, like so:

``` yaml
api.posts:
    type: rest
    resource: My\Bundle\ApiBundle\Controller\PostsController
```

Then I added, to avoid collisions:

``` yaml
api.posts:
    type: rest
    resource: My\Bundle\ApiBundle\Controller\PostsController
    name_prefix: api_
```

However, once I add `name_prefix`, I get the following:

```
  [InvalidArgumentException]                                                                                                                              
  Yaml routing loader does not support given key: "name_prefix". Expected one of the (type, resource, prefix, pattern, options, defaults, requirements).  
```

Any ideas?
