### ISSUE TITLE
Request's query bag is empty, when it shouldn't

### ISSUE THREAD

**Issue by kptLucek** [FriendsOfSymfony/FOSRestBundle#1298]
Hi there, and happy new year :)

First of all, i've created an endpoint to search user based on some credentials,

**Controller's action**
```php
	/**
	 * @param Request               $request
	 * @param ParamFetcherInterface $paramFetcherInterface
	 *
	 * @ApiDoc(
	 *      section="User",
	 *      resource=true,
	 *      description="Search user",
	 *      requirements={
	 *          {
	 *              "name"="phrase",
	 *              "dataType"="string",
	 *              "requirement"="\[a-zA-Z0-9\s\@]+",
	 *              "description"="Part of 'username', 'email', 'name' or 'surname'"
	 *          }
	 *      }
	 * )
	 *
	 * @Rest\QueryParam("phrase", nullable=false, allowBlank=false, description="User search string.", array=false, requirements="[a-zA-Z0-9\@\s]+", strict=true)
	 *
	 * @return Response
	 */
	public function getFindUserAction(Request $request, ParamFetcherInterface $paramFetcherInterface)
	{
		$view = $this->view(['phrase' => $paramFetcherInterface->all(), 'query' => $request->query->all()]);

		return $this->handleView($view);
	}
```
**app/config/routing.yml**

```yml
api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api
    options:
        i18n: false
```

**ApiBundle/Resources/config/routing.yml**
```yml
api_user_search:
    path: /user/search
    defaults:
        _controller: ApiBundle:User/UserEndpoint:getFindUser
    methods: [GET]
```

**fos_rest.yml**
```yml
fos_rest:
    format_listener: true
    routing_loader:
        default_format: json
        include_format: false
    view:
        view_response_listener: force
        force_redirects:
          html: true
        formats:
            jsonp: true
            json: true
            xml: false
            rss: false
        templating_formats:
            html: true
        mime_types:
            json: ['application/json', 'application/x-json']
            rss: 'application/rss+xml'
            jpg: 'image/jpeg'
            png: 'image/png'
        jsonp_handler: ~
    body_listener: true
    param_fetcher_listener: force
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    routing_loader:
        default_format: ~
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    serializer:
        groups:
            - REST
```

And now, when accessing **/user/search?phrase=xyz** im getting this:
```json
{"code":400,"message":"Query parameter \"phrase\" is empty"}
```

**Server parameters**
REQUEST_URI 	/api/user/search?phrase=xyz

![profiler](https://cloud.githubusercontent.com/assets/6822027/12070419/36190b1c-b074-11e5-9fa9-608c0d474eea.PNG)

Thanks for help

P.S. **When i'm accessing non-fosrest route, everything's fine**
