### ISSUE TITLE
Trouble when upgrade from 1.7.7 to 044f4e0

### ISSUE THREAD

**Issue by marcobarcaro** [FriendsOfSymfony/FOSRestBundle#1301]
Hi,
I have two bundle: DemoBundle and ApiBUndle. 
I've upgraded SF from 2.7 to 2.8 and FOSRestBundle (dev-master) is not working anymore. I guess the problem is related to view_response_listener. When I use this configuration:

```yaml
fos_rest:
    param_fetcher_listener:
        enabled: true
    routing_loader:
        default_format: json
    view:
        view_response_listener:
            enabled: true
            force: false
```

I got this exception "The controller must return a response" from any controller on DemoBundle. 

 DEBUG - Notified event "kernel.view" to listener "FOS\RestBundle\EventListener\ViewResponseListener::onKernelView".
CRITICAL - Uncaught PHP Exception LogicException: "The controller must return a response (Array())." at ...\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php line 157 

Maybe this is due to:
"Note that it is necessary to disable view annotations in SensioFrameworkExtraBundle so that FOSRestBundle can take over the handling. However, FOSRestBundle will do this automatically but it does not override any explicit configuration. So make sure to remove or disable the following setting:"
http://symfony.com/doc/master/bundles/FOSRestBundle/view_response_listener.html

Best regards
