### ISSUE TITLE
Exception was thrown while handling error pages

### ISSUE THREAD

**Issue by glasset** [FriendsOfSymfony/FOSRestBundle#1302]
when a page return 404 not found, fos rest throw a exception while the view ('twigbundle:exception:error404' for example) is render like is unable to find template.
for info i have overriding the default error templates

`An Exception was thrown while handling: Not Found`

this error is only in prod with `app_dev.php` it's work fine

config.yml
```yml
# Twig Configuration
twig:
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# JMS Serializer
jms_serializer:
    metadata:
        auto_detection: true

# fos rest 
fos_rest:
    format_listener:
        rules:
            - { path: '^/api/', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true }
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': true
    view:
        exception_wrapper_handler:  null
        view_response_listener: force
        formats:
            json: true
            xml:  false
    routing_loader:
        default_format: json
    serializer:
        serialize_null: true
    param_fetcher_listener: true
    body_listener: true
    access_denied_listener:
        json: true
```

thanks for your time

**Comment by xabbuh** [comment]
Thanks for the bug report @glasset. Can you check if your issue is the same as #1301?

**Comment by glasset** [comment]
i don't think because there is my version:
`fos-rest: 1.7.7`
`symfony: 2.7` 

the throw trigger in the render but no message of exception just 'not found' (status text of 404)
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/1.7/View/ViewHandler.php#L390

maybe i miss something in `fos_rest` conf ?

**Comment by Ener-Getick** [comment]
Can we have more informations please? It would be easier if we had your entire configuration and the stack of the error.

**Comment by glasset** [comment]
```yml
imports:
    - { resource: ../parameters/parameters.yml }
    - { resource: ../security.yml }
..

monolog:
    handlers:
        custom_app:
            type: stream
            path:  %kernel.root_dir%/logs/custom_app.log
            level: info
            channels: [custom_app]

framework:
    esi:             { enabled: true }
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: v1
        assets_version_format: %%s?v=%%s
        assets_base_urls:
            ssl:
                - %cdn_url%

    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: [172.16.0.0/12]
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: session.handler.pdo
        cookie_domain: .com
        cookie_lifetime: 31536000
        gc_maxlifetime: 31536000
    fragments:       { path: /_proxy }
    http_method_override: true
    default_locale: %locale%
    translator:      { fallback: "%locale%" }

parameters:
    pdo.db_options:
        db_table:    session
        db_id_col:   session_id
        db_data_col: session_value
        db_time_col: session_time

# Twig Configuration
twig:
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        typeform_uid:     "%typeform_uid%"
        websiteName:  "%website_name%"
        urlBaseCron: "%url_mail_cron%"
        stripe_key_public: "%stripe_key_public%"
        asseticVersion: "?v=9"
        cdnUrl: "%cdn_url%"
    form:
        resources:
             - ':Form:form_div_layout.html.twig'
             - 'SonataCoreBundle:Form:datepicker.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [...]
    filters:
        cssrewrite: ~
        jsqueeze: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
            apply_to: "\.less$"
            formatter: "compressed"
            preserve_comments: "false"

services:
    twig.extension.debug:
        class:        Twig_Extension_Debug
        tags:
             - { name: 'twig.extension' }
    pdo:
        class: PDO
        arguments:
            - "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%"
            - %database_user%
            - %database_password%
        calls:
            - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION
    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: ["@pdo", "%pdo.db_options%"]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"
        schema_filter: ~^(?!(locations|session|threads|tickets))~

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        # metadata_cache_driver: apc
        # query_cache_driver: apc
        # result_cache_driver: apc

# Swiftmailer Configuration
swiftmailer:
    transport: "smtp"
    port: 465
    encryption: "ssl"
    auth_mode: login
    host:      "com"
    username: ""
    password:  ""
    spool:     { type: memory }

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
sonata_admin:
    title:    
    security:
        handler: sonata.admin.security.handler.role
        information:
            EDIT: EDIT
            LIST: LIST
            CREATE: CREATE
            VIEW: VIEW
            DELETE: DELETE
            EXPORT: EXPORT
            OPERATOR: OPERATOR
            MASTER: MASTER

sonata_doctrine_orm_admin:
    # default value is null, so doctrine uses the value defined in the configuration
    templates:
        form:
            - SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig

stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: ".tinymce"
    language: %locale%
    theme:
        simple:
            theme: "modern"

knp_snappy:
   pdf:
      binary: "%kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64"

# JMS Serializer
jms_serializer:
    metadata:
        auto_detection: true

# NELMIO API Doc
nelmio_api_doc:
    name: API

# FOS Rest
fos_rest:
    format_listener:
        rules:
            - { path: '^/api/doc', priorities: ['html'], fallback_format: html, prefer_extension: false }
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true }
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': true
    view:
        exception_wrapper_handler:  null
        view_response_listener: force
        formats:
            json: true
            xml:  false
    routing_loader:
        default_format: json
    serializer:
        serialize_null: true
    param_fetcher_listener: true
    body_listener: true
    access_denied_listener:
        json: true

lexik_jwt_authentication:
    private_key_path: %jwt_private_key_path%
    public_key_path:  %jwt_public_key_path%
    pass_phrase:      %jwt_key_pass_phrase%
    token_ttl:        %jwt_token_ttl%

fos_js_routing:
    routes_to_expose:
        - "^api_.*"
```

website.com/fake-name: 
render
```
An Exception was thrown while handling: Not Found
```

log/prod:
```
request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /fake-name"" at /home/website/app/cache/prod/classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /fake-name" at /home/website/app/cache/prod/classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /home/website/app/cache/prod/appProdUrlMatcher.php:2848)"}
```

log/dev

```
[2016-01-09 10:52:04] event.DEBUG: Notified event "kernel.exception" to listener "FOS\RestBundle\EventListener\AccessDeniedListener::onKernelException". [] []
[2016-01-09 10:52:04] event.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\Security\Http\Firewall\ExceptionListener::onKernelException". [] []
[2016-01-09 10:52:04] event.DEBUG: Listener "Symfony\Component\Security\Http\Firewall\ExceptionListener::onKernelException" stopped propagation of the event "kernel.exception". [] []
[2016-01-09 10:52:04] event.DEBUG: Listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelException" was not called for event "kernel.exception". [] []
[2016-01-09 10:52:04] event.DEBUG: Listener "Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException" was not called for event "kernel.exception". [] []
[2016-01-09 10:52:04] event.DEBUG: Notified event "kernel.response" to listener "Sonata\BlockBundle\Cache\HttpCacheHandler::onKernelResponse". [] []
[2016-01-09 10:52:04] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2016-01-09 10:52:04] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\SurrogateListener::onKernelResponse". [] []
[2016-01-09 10:52:04] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\Security\Http\RememberMe\ResponseListener::onKernelResponse". [] []
[2016-01-09 10:52:04] event.DEBUG: Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelResponse". [] []
[2016-01-09 10:52:04] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelResponse". [] []
[2016-01-09 10:52:04] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Bundle\WebProfilerBundle\EventListener\WebDebugToolbarListener::onKernelResponse". [] []
[2016-01-09 10:52:04] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\SaveSessionListener::onKernelResponse". [] []
[2016-01-09 10:52:04] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\StreamedResponseListener::onKernelResponse". [] []
[2016-01-09 10:52:04] event.DEBUG: Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelFinishRequest". [] []
[2016-01-09 10:52:04] event.DEBUG: Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelFinishRequest". [] []
[2016-01-09 10:52:04] event.DEBUG: Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelFinishRequest". [] []
[2016-01-09 10:52:04] event.DEBUG: Notified event "kernel.finish_request" to listener "Symfony\Component\Security\Http\Firewall::onKernelFinishRequest". [] []
[2016-01-09 10:52:05] event.DEBUG: Notified event "kernel.terminate" to listener "Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener::onTerminate". [] []
[2016-01-09 10:52:05] event.DEBUG: Notified event "kernel.terminate" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelTerminate". [] []
``
