### ISSUE TITLE
Configuration for loading route annotations from a directory

### ISSUE THREAD

**Issue by aguidis** [FriendsOfSymfony/FOSRestBundle#1377]
Since this merged [PR](https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1339/files) we should be able to load all route annotations in a folder.

I tried this syntax : 

```yml
api:
    type: rest
    resource: "@AppBundle/Controller/"
```

But I still have this error message : 

> Can't find class for controller "@AppBundle/Controller/" in /home/me/src/AppBundle/Resources/config/api-routing.yml (which is being imported from "/home/me/app/config/routing.yml").

I fetched the version with the tag "2.0.0-BETA1"

```yml
"friendsofsymfony/rest-bundle": "2.0.0-BETA1",
```
And I checked if I had the class ``FOS\RestBundle\Routing\Loader\DirectoryRouteLoader`` and it's the case so I should not use the right syntax I think

Thanks for your help

**Comment by Ener-Getick** [comment]
The short syntax is not supported yet, you have to use the full directory path.

**Comment by aguidis** [comment]
```yml

# app/config/routing.yml

coucou_api:
    type:     rest
    prefix:   /api/{version}
    resource: "@AppBundle/Resources/config/api-routing.yml"
```

```yml

# src/AppBundle/Resources/config/api-routing.yml
api:
    type: rest
    resource: "src/AppBundle/Controller"
```

![image](https://cloud.githubusercontent.com/assets/1856652/13603676/2d054b1c-e53f-11e5-96f8-9ccd67696d12.png)

but I have this message : 

> Class could not be determined for Controller identified by "src/AppBundle/Controller" in /home/me/src/AppBundle/Resources/config/api-routing.yml (which is being imported from "/home/me/app/config/routing.yml").
