### ISSUE TITLE
Warning: ReflectionObject::__construct() expects parameter 1 to be object, null given

### ISSUE THREAD

**Issue by howardem** [FriendsOfSymfony/FOSRestBundle#1381]
Hello, 

I'm building a REST API layer using Symfony 2.8 and FOS Rest version 2.0.0-BETA2. Every time I send a request to the API I get a 500 error:

```
       "message": "Warning: ReflectionObject::__construct() expects parameter 1 to be object, null given",
        "class": "Symfony\Component\Debug\Exception\ContextErrorException",
        "trace": [
          {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "C:\xampp\htdocs\cms-api\vendor\friendsofsymfony\rest-bundle\EventListener\ViewResponseListener.php",
            "line": 153,
            "args": []
          },
          {
            "namespace": "Symfony\Component\Debug",
            "short_class": "ErrorHandler",
            "class": "Symfony\Component\Debug\ErrorHandler",
            "type": "->",
            "function": "handleError",
            "file": null,
            "line": null,
            "args": [
              [
                "string",
                "2"
              ],
              [
                "string",
                "ReflectionObject::__construct() expects parameter 1 to be object, null given"
              ],
              [
                "string",
                "C:\xampp\htdocs\cms-api\vendor\friendsofsymfony\rest-bundle\EventListener\ViewResponseListener.php"
              ],
              [
                "string",
                "153"
              ],
              [
                "array",
                {
                  "template": [
                    "object",
                    "FOS\RestBundle\Controller\Annotations\View"
                  ],
                  "controller": [
                    "null",
                    null
                  ],
                  "action": [
                    "null",
                    null
                  ],
                  "arguments": [
                    "array",
                    []
                  ]
                }
              ]
            ]
          },
		  
```
This the resource I'm requesting. Traced the error and when the response is being dispatched it seems like the bundle implementation loses the information about the controller. This was working perfectly until Friday. At that time I was using FOS Rest 2.0.x-dev and everything was working fine. 

```
    /**
     * @REST\View()
     * @REST\Get("")
     */
    public function getDotInfosAction() {
        $dotInfos = $this->dotInfoService->findAll();
        return array('dotInfos' => $dotInfos);
    }	
```

This is my FOS configuration:
```
# FoS Rest
fos_rest:
    routing_loader:
        include_format: false    
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
    view:
        view_response_listener: 'force'
        mime_types:
            json: ['application/json', 'application/json; version=1.0']
            xml: ['application/xml', 'application/xml; version=1.0']  
    versioning:
        enabled: true
        resolvers:
            query: true
            custom_header: true
            media_type:
                enabled: true
                regex: '/(v|version)=(?P<version>[0-9\.]+)/'
        guessing_order:
            - query
            - custom_header
            - media_type	
```
