### ISSUE TITLE
array_key_exists error for enity POST with ManyToOne relation

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfSymfony/FOSRestBundle#1403]
Partially related to #1236.

I have two entities: `IpV6Range` and `IpGroup`.

Each `IpV6Range` has one `IpGroup`.

`IpV6Range` class:

```php
/**
 * @ORM\Table(name="ip_v6_range")
 * @ORM\Entity
 * @UniqueEntity("baseIp")
 */
class IpV6Range
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", unique=true)
     * @Assert\NotBlank
     * @Assert\Ip(version="6_public")
     */
    private $baseIp;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Range(min="1", max="128")
     */
    private $subnet;

    /**
     * @var IpGroup
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\IpGroup", inversedBy="ipV6Ranges", cascade={"persist"})
     * @ORM\JoinColumn(referencedColumnName="id", nullable=true)
     */
    private $group;

    /**
     * @var IpV6[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\IpV6", mappedBy="range", cascade={"persist"}, orphanRemoval=true)
     * @Assert\Valid
     * @Assert\Count(min="1")
     */
    private $ips;

    // Getters / Setters
}
```

`IpGroup` class:

```
/**
 * @ORM\Table
 * @ORM\Entity
 */
class IpGroup
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank
     * @Assert\Length(max="100")
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=20)
     * @Assert\NotBlank
     * @Assert\Length(max="20")
     * @Assert\Regex("/^[a-z_]+$/", message="Only characters and underscores.")
     */
    private $code;

    /**
     * @var Ip[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\IpV6Range", mappedBy="group")
     */
    private $ipV6Ranges;

    // Getters / Setters
}
```

My serializer entities configuration:

```yaml
AppBundle\Entity\IpGroup:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [list_admin, details_admin]
        name:
            expose: true
            groups: [list_admin, details_admin]
        code:
            expose: true
            groups: [list_admin, details_admin]

AppBundle\Entity\IpV6Range:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [list_admin, details_admin]
        baseIp:
            expose: true
            groups: [list_admin, details_admin]
        subnet:
            expose: true
            groups: [list_admin, details_admin]
        group:
            expose: true
            groups: [details_admin]
```

And finally, my REST controller `postAction`:

```php
/**
 * @param IpV6Range                        $range
 * @param ConstraintViolationListInterface $validationErrors
 *
 * @QueryParam(name="range", key=null)
 * @ParamConverter("range", converter="fos_rest.request_body")
 *
 * @return View
 */
public function postAction(IpV6Range $range, ConstraintViolationListInterface $validationErrors)
{
    if ($validationErrors->count() > 0) {
        return $this->handleBodyValidationErrorsView($validationErrors);
    }

    $em = $this->getDoctrine()->getManager();
    $em->persist($range);
    $em->flush();

    $view = $this->view($range);
    $view->getSerializationContext()->setGroups('details_admin');

    return $view;
}
```

If I try an ip range creation using `POST` method with this data:

```json
{
    "base_ip": "2a01:8760:2:3021::1",
    "subnet": "64",
    "group": 1
}
```

I obtain the following error:

```json
{
  "error": {
    "code": 500,
    "message": "Internal Server Error",
    "exception": [
      {
        "message": "Warning: array_key_exists() expects parameter 2 to be array, integer given",
        "class": "Symfony\\Component\\Debug\\Exception\\ContextErrorException",
        "trace": [
          {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "/code/vendor/jms/serializer/src/JMS/Serializer/GenericDeserializationVisitor.php",
            "line": 165,
            "args": []
          },
          {
            "namespace": "Symfony\\Component\\Debug",
            "short_class": "ErrorHandler",
            "class": "Symfony\\Component\\Debug\\ErrorHandler",
            "type": "->",
            "function": "handleError",
            "file": null,
            "line": null,
            "args": [
              [
                "string",
                "2"
              ],
              [
                "string",
                "array_key_exists() expects parameter 2 to be array, integer given"
              ],
              [
                "string",
                "/code/vendor/jms/serializer/src/JMS/Serializer/GenericDeserializationVisitor.php"
              ],
              [
                "string",
                "165"
              ],
              [
                "array",
                {
                  "metadata": [
                    "object",
                    "JMS\\Serializer\\Metadata\\PropertyMetadata"
                  ],
                  "data": [
                    "string",
                    "1"
                  ],
                  "context": [
                    "object",
                    "JMS\\Serializer\\DeserializationContext"
                  ],
                  "name": [
                    "string",
                    "id"
                  ]
                }
              ]
            ]
          },
```
