### ISSUE TITLE
Version annotation not adding route condition for API versioning

### ISSUE THREAD

**Issue by angrygreenfrogs** [FriendsOfSymfony/FOSRestBundle#1491]
I'm having trouble with getting the @Version annotation to work. It does not seem to be causing the expected route condition to be added.

I've installed the latest bundle 2.0 (commit f4ce3e9ed88b41c449aa45b120d880723e5f75d7)

I'm trying to make use of the API versioning system with the query parameter style "?version=v1".

I have two separate controllers setup for testing, one for v1 and the other for v2.

I'm trying to make use of the Version annotation to select the correct controller.

config.yml
```
fos_rest:
    versioning:
        enabled: true
        default_version: v1
        resolvers:
            query: 
                enabled: true
                parameter_name: version
    param_fetcher_listener: true
    format_listener:
        rules:
            - { path: '^/api/', fallback_format: json }
            - { path: '^/', stop: true }
```

Version 2 controller
```
/**
 * @Version("v2")
 */
class Testv2Controller extends FOSRestController implements ApiKeyAuthenticatedController
{
    /**
     * Test
     * @Rest\View()
     * @Route("/api/function/test.{_format}",defaults={"_format": "json"})
     * @Method("POST")
     * @RequestParam(name="apikey", requirements="[a-zA-Z0-9]{32}", allowBlank=false, strict=true, description="Application API Key")
     * @param ParamFetcher $paramFetcher
     * @return Response
     * @throws HttpException on application failure
     */
    public function getTestAction(ParamFetcher $paramFetcher)
    {
....
```

Version 1 controller
```
/**
 * @Version("v1")
 */
class Testv1Controller extends FOSRestController implements ApiKeyAuthenticatedController
{
    /**
     * Test
     * @Rest\View()
     * @Route("/api/function/test.{_format}",defaults={"_format": "json"})
     * @Method("POST")
     * @RequestParam(name="apikey", requirements="[a-zA-Z0-9]{32}", allowBlank=false, strict=true, description="Application API Key")
     * @param ParamFetcher $paramFetcher
     * @return Response
     * @throws HttpException on application failure
     */
    public function getTestAction(ParamFetcher $paramFetcher)
    {
....
```

Basically the problem is that calling my API with ?version=v1 or ?version=v2 has no effect and the version 1 controller is always called.

However, if I manually change the routing annotations like this:
v2 route
```
* @Route("/api/function/test.{_format}",defaults={"_format": "json"},condition="request.attributes.get('version') == 'v2'")
```

v1 route
```
* @Route("/api/function/test.{_format}",defaults={"_format": "json"},condition="request.attributes.get('version') == 'v1'")
```

Then it works exactly as expected and the correct function is called. So I'm pretty convinced I've narrowed this down to the @Version annotation not working for me, but for the life of me I can't figure out why.
