### ISSUE TITLE
Symfony serializer not working on version >= 1.8

### ISSUE THREAD

**Issue by zim32** [FriendsOfSymfony/FOSRestBundle#1498]
Trying version 1.8 break symfony serialization. Objects get serialized to [] .

**Comment by xabbuh** [comment]
@zim32 Can you provide more information on how you configured your application and if you added some custom code that is involved?

**Comment by zim32** [comment]
No custom code. Just std configuration.

```
//app/config/config.yml

framework:
    serializer:
      enabled: true

fos_rest:
    serializer:
      serialize_null: true
    param_fetcher_listener: true
    routing_loader:
        default_format: json
```

```
//Controller

$data = ... // array of simple plain object with public getters
$view = $this->view(['status'=>'ok', 'data'=>$data]);
return $this->handleView($view);
```
