### ISSUE TITLE
Prefix is ignored with annotations

### ISSUE THREAD

**Issue by JHGitty** [FriendsOfSymfony/FOSRestBundle#1508]
```php
use FOS\RestBundle\Controller\Annotations as Rest;

class CategoryController extends Controller
{
    /**
     * @Rest\Get("/category/{name}", name="api_category", options={"method_prefix": false})
     */
    public function getCategoryAction($name)
    {
        return 'test';
    }
```

```yaml
api:
    prefix:   /api
    type:     rest
    resource: "@AppBundle/Controller/Api/"
```

This will result into `/category/{name}` instead of `/api/category/{name}`. Why?

Tested on `2.0.0-BETA3` and latest `dev-master`.

**Comment by Ener-Getick** [comment]
The ``/api`` prefix is managed by symfony. Do you load your routes elsewhere ?

**Comment by JHGitty** [comment]
Yep. So this is the issue. My `routing.yml` file:

```yaml
api:
    prefix:   /api
    type:     rest
    resource: "@AppBundle/Controller/Api/"

app:
    type:     annotation
    resource: "@AppBundle/Controller/"
```
