### ISSUE TITLE
Can't use container parameter in defaults and requirements of QueryParam annotation

### ISSUE THREAD

**Issue by Chrisp1tv** [FriendsOfSymfony/FOSRestBundle#1528]
Hi :) After upgrading FOSRestBundle from 1.7 to 2.0, I still can't use a container parameter in QueryParam annotation. Maybe something wrong in my code ? Thanks :)

```yaml
# FOSRestBundle Configuration
fos_rest:
    param_fetcher_listener: true
    body_listener:
        enabled: true
    format_listener:
        enabled: true
    view:
        view_response_listener:
            enabled: true
        formats:
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
    routing_loader:
        default_format: json
        include_format: false
```

```yaml
parameters:
    locale: fr
```

```php
use FOS\RestBundle\Controller\Annotations as Rest;
 // [...]
    /**
     * @Rest\QueryParam(name="locale", default="%locale%")
     * @Rest\QueryParam(name="offset", requirements="\d+", default=AppController::DEFAULT_OFFSET_GET_ENTRIES_ACTION)
     * @Rest\QueryParam(name="limit", requirements="\d+", default=AppController::DEFAULT_LIMIT_GET_ENTRIES_ACTION)
     * @Rest\View(serializerGroups={"list"})
     *
     * @param ParamFetcher $paramFetcher
     * @return array|null
     */
    public function getEntriesAction(ParamFetcher $paramFetcher)
    {
        dump($paramFetcher->get('locale')); // Returns "%locale%", not the parameter identified by "locale"
    }
```
