### ISSUE TITLE
Incorrect Content-Type header on PHP errors

### ISSUE THREAD

**Issue by bblue** [FriendsOfSymfony/FOSRestBundle#1537]
For all exceptions thrown by my application FOSRestBundle will correctly serialize the exception and return my expected format.

However, whenever there is a PHP error, it will always return a Content-Type of `text/html; charset=UTF-8,application/json` or` text/html; charset=UTF-8,text/xml; charset=UTF-8`

The content is still serialized correctly (testet with json and xml), so not big issue, but more of an annoycance. Appears to be a bug somewhere though...

**Comment by bblue** [comment]
Did a bit more digging, and it appears the requested format is dropped in the subrequest to `fos_rest.exception.twig_controller:showAction`. 

I also tried to remove the two rules below, and I then received a Content-Type of `text/html; charset=UTF-8,text/html; charset=UTF-8`

```
// config.yml
fos_rest:
    format_listener:
        rules:
            - { path: '^/api', priorities: [ 'json', 'xml', 'html' ], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }
```
