### ISSUE TITLE
Format Listener schould omit content-type header on empty content

### ISSUE THREAD

**Issue by akomm** [FriendsOfSymfony/FOSRestBundle#1555]
```yml
fos_rest:
  format_listener:
    enabled: true
    rules:
      - { path: ^/api, priorities: [ json ], fallback_format: json, prefer_extension: false }
```

When some routes under ^/api do not return any data, format listener should omit content-type: `application/json`, So it should do for other formats. If there are cases where it would not make any sense, maybe add it as an option, so you can tell to omit content-type if response is empty on json format.
