### ISSUE TITLE
Symfony serializer default configuration not supported when no group is used

### ISSUE THREAD

**Issue by Abam** [FriendsOfSymfony/FOSRestBundle#1556]
With the new Serializer Context object, groups are set to an empty array by default.  This behavior make FOSRestBundle incompatible with the defaut Symfony serializer configuration.

Symfony Framework serializer is using by default the ObjectNormalizer. When I try to serialize an object without a group, no attribute is shown.

The only fix is to activate the GetSetMethodNormalizer.

```yml
services:
    getset_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }
```

To fix this, Context must return `null` if no serializer group is specified (using the SymfonySerializerAdapter may be a good choice).
