### ISSUE TITLE
Format Listener should return 406 with no content when fallback_format is not defined instead of falling back to text/html

### ISSUE THREAD

**Issue by akomm** [FriendsOfSymfony/FOSRestBundle#1558]
Having:

```yml
fos_rest:
  format_listener:
    enabled: true
    rules:
      - { path: ^/api, priorities: [ json ], fallback_format: json, prefer_extension: false }
```

When I send a `GET` request to `/api/*` having header `Accept: text/plain` I get back a response with `Content-Type: application/json`. So far it is correct when using fallback format.

Having:
```yml
fos_rest:
  format_listener:
    enabled: true
    rules:
      - { path: ^/api, priorities: [ json ], prefer_extension: false }
```

When I send a `GET` request to `/api/*` having header `Accept: text/plain` I get back a response with `Content-Type: text/html; charset=UTF-8`, status code 500 with HTML exception because no template was found. Here I would expect an status 406 with no body and no `content-type` header.

**Comment by Ener-Getick** [comment]
I agree it may look weird for your case but [`html` is used as the default fallback](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/DependencyInjection/Configuration.php#L316).
You must explicitly remove it:
```yml
fos_rest:
  format_listener:
    enabled: true
    rules:
      - { path: ^/api, priorities: json, prefer_extension: false, fallback_format: ~ }
```
