### ISSUE TITLE
XML take priority

### ISSUE THREAD

**Issue by MatthieuMota** [FriendsOfSymfony/FOSRestBundle#1563]
I've question about FormatNegotiator. I wan't my API purpose : 
http://myapi.com/users -> Return JSON
http://myapi.com/users.json -> Return JSON
http://myapi.com/users.xml -> Return XML

Now, I've :
http://myapi.com/users -> Return XML
http://myapi.com/users.json -> Return JSON
http://myapi.com/users.xml -> Return XML

In fos_rest config, I've simply put format_listener with a rule :

```
    format_listener:
        rules:
            - { path: '^/', priorities: ['json', 'xml'] }
```

By any logic, if format is not requested by client, the first element of priorities is returned ?
I've checked FormatNegotiator and the best format is get by compare header with priorities array (with parent method GetBest from willdurand/negotiation). But header always contains xml !

```
routing_loader:
        default_format: json
```

default_format option doesn't influence that. I can fix that or it's voluntary ?

**Comment by Soullivaneuh** [comment]
Which version of this bundle do you have? I have 2.0.0 and here is my complete config:

```yaml
fos_rest:
    routing_loader:
        default_format: json
    body_converter:
        enabled: true
        validate: true
    serializer:
        serialize_null: true
    view:
        formats:
            xml:  false
            json: true
            rss:  false
            yml:  true
        view_response_listener: force
    param_fetcher_listener: force
    format_listener:
        rules:
            - { path: '^/api/', priorities: ['json', 'yml'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true } # FOSRest should not handle other routes than API
    versioning:
        enabled: true
        resolvers:
            media_type:
                enabled: true
```

And I have json if I don't specify any extension on the URL.
