### ISSUE TITLE
Warning: array_merge(): Argument #1 is not an array

### ISSUE THREAD

**Issue by numediaweb** [FriendsOfSymfony/FOSRestBundle#1617]
I have this issue in vendor/friendsofsymfony/rest-bundle/EventListener/MimeTypeListener.php at line 57:
```php
 foreach ($this->mimeTypes as $format => $mimeTypes) {
                if (method_exists(Request::class, 'getMimeTypes')) {
                    $mimeTypes = array_merge($mimeTypes, Request::getMimeTypes($format)); // error if format is jpg
                } elseif (null !== $request->getMimeType($format)) {
                    $class = new \ReflectionClass(Request::class);
                    $properties = $class->getStaticProperties();
```
I am using PHP 5.6.25 with:
```
"symfony/symfony": "3.1.*",
"doctrine/orm": "^2.5.5",
 "friendsofsymfony/rest-bundle": "^2.1",
```

**Comment by numediaweb** [comment]
I fixed it temporary by disabling the jpg and png mime types in config.yml
```
# FOS REST Bundle
fos_rest:
    body_listener: true
    format_listener:  true
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            jsonp: true
            json: true
            xml: false
            rss: false
        mime_types:
            json: ['application/json', 'application/x-json']
            #jpg: 'image/jpeg'
            #png: 'image/png'
        jsonp_handler: ~
```
