### ISSUE TITLE
Working with JSON form in a POST action

### ISSUE THREAD

**Issue by NaeiKinDus** [FriendsOfSymfony/FOSRestBundle#1620]
Hello,

I am trying to create a POST action using forms and JSON content, but I can't figure out for the life of me how to get that working.
Is it possible to use Symfony's forms in a controller to automatically handle input errors ? If I just return the $form, Symfony will complain about a missing TWIG template (which is normal); if I create a TWIG page that contains only "{{ form_errors(form) }}" then I'll get no content, and if I just do "{{ form(form) }}" I'll get an HTML form (and no validation errrors).
Previously when working with ORM limitations to validate data (@Assert and @Serializer\*) everything was fine, but since the change to TWIG views and JSON-only exchanges I can no longer rely on the forms :-/

Here is the controller's code:
```php
    /**
     * @Route("/customers")
     * @ApiDoc(
     *      resource=false,
     *      input="NetDev\CoreBundle\Form\CustomerType",
     *      description="Create a new customer",
     *      section="Customers",
     *      statusCode={
     *          201="Action successful",
     *          403="Authorization required but incorrect / missing information or insufficient rights",
     *          500="Returned if action failed for unknown reasons"
     *      }
     *  )
     *
     * --View(template="NetDevRestBundle:Customers:add.json.twig", templateVar="form", statusCode=400)
     * @View(templateVar="form", statusCode=400)
     * @param Request $request
     * @return \FOS\RestBundle\View\View
     */
    public function postCustomerAction(Request $request)
    {
        $data = json_decode($request->getContent(), true);
        $manager = $this->getManager();
        $customer = new Customer();
        $form = $this->getForm($customer);
        $form->handleRequest($data);
        //$form->submit($data);
        if ($form->isValid()) {
            $manager->create($customer);
            return; /* will be redirected */
        }
        /* return $this->view((string)$form->getErrors())
                ->setTemplate('NetDevRestBundle:Common:form_error.json.twig'); */ // -> empty string
       return $form;
    }
```

And the bundle configuration:

```yaml
fos_rest:
  param_fetcher_listener: true
  body_listener: true
  format_listener:
    enabled: true
  view:
    view_response_listener: 'force'
    formats:
      json: true
    templating_formats:
        json: true
    force_redirects:
      html: true
    failed_validation: HTTP_BAD_REQUEST
    default_engine: twig
  routing_loader:
    include_format: false
    default_format: json
  serializer:
    serialize_null: true

sensio_framework_extra:
  view:
    annotations: true
```

Any help would be much appreciated.
