### ISSUE TITLE
Ability to disable fos rest array normalization for certain paths

### ISSUE THREAD

**Issue by steffenbrem** [FriendsOfSymfony/FOSRestBundle#1660]
When using the `FOSOAuthServerBundle` in combination with `FOSRest` you end up with an issue that the array normalizer converts an token request from underscored to camelcase. Because of this the token request will fail, since the OAuth2 server needs the parameters to be underscored.

To fix this I tried doing this:
```
fos_rest:
    format_listener:
        rules:
            - { path: '^/api/oauth', stop: true }
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true }
```

But this doesnt solve it, since from what I can see the array normalization takes place for every request that is either `POST`, `PUT`, `PATCH` etc.

Is there currently a good way to solve this? It should be possible to disable the request manipulation that fos rest does for certain requests.
