### ISSUE TITLE
Unexpected Content-Type on Unrecognized Extensions w/ prefer_extension

### ISSUE THREAD

**Issue by JProffitt71** [FriendsOfSymfony/FOSRestBundle#1661]
I'm having an issue with counter-intuitive content-types for requests that have unrecognized extensions. Here is the minimal configuration to create this issue:

```
fos_rest:
    format_listener:
        rules:
            - { path: '^/', priorities: ['html', 'json', 'xml'], prefer_extension: true}
```

And a sample problematic request:
Location: /js/main.min.js.map
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8

The format negotiator cannot resolve .map to a mime-type, so it just gives the last mime-type a q of 2.0:
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8; q=2.0

This causes it to weight anything not listed in the Accept header higher, and in this case it returns a Content-Type of application/json (the first format in my priorities thats not listed in Accept header).

This is extremely counter-intuitive. I would expect when it couldn't determine the mime-type from the extension, for it to not modify the Accept header at all and do content negotiation like prefer_extension was off.
