### ISSUE TITLE
Dictoros response class is being converted to json

### ISSUE THREAD

**Issue by c410-f3r** [FriendsOfSymfony/FOSRestBundle#1665]
Forced json format in the view layer and returned a Dictoros response from the controller, now the Dictoros class itself is being converted to json:

**Composer**
```
"require": {
  "symfony/psr-http-message-bridge": "^1.0",
  "zendframework/zend-diactoros": "^1.3"
}
```

**View layer**
```
fos_rest:
  view:
    default_engine: null
    view_response_listener: 'force'
    formats:
      json: true
```

**Controller**
```
$symfonyResponse = new Response('{"example":10}');
$psr7Factory = new DiactorosFactory();
return $psr7Factory->createResponse($symfonyResponse);
```

**Response**
```
{"statusCode":200,"reasonPhrase":"OK","protocolVersion":"1.0","headers":{"cache-control":["no-cache, private"]},"body":{"size":14,"seekable":true,"writable":true,"readable":true,"contents":"","metadata":{"wrapper_type":"PHP","stream_type":"TEMP","mode":"w+b","unread_bytes":0,"seekable":true,"uri":"php:\/\/temp"}}}
```

This error is not reproduced using the default response: `return $this->json(['example' => 10]);`
