### ISSUE TITLE
Non-existent service "fos_rest.view_handler"

### ISSUE THREAD

**Issue by pdias** [FriendsOfSymfony/FOSRestBundle#1671]
Hello,

I'm using the dev-master branch and i get this error:

``You have requested a non-existent service "fos_rest.view_handler". Did you mean this: "fos_rest.view_handler.default"?``

In AppKernel i have declared:

``new FOS\RestBundle\FOSRestBundle()``

Can someone  help me?

Thanks in advance,

Paulo Dias

**Comment by GuilhemN** [comment]
It looks like we should not have merged https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1655 after all... I'll provide a better asap.

**Comment by jpillias** [comment]
Any du date for this fix ? 
Best regards.

**Comment by jpillias** [comment]
Thank you.

I've done the job with an alias : 

```yaml
    # for bug fix fos rest bundle
    fos_rest.view_handler:
        alias: fos_rest.view_handler.default
```

**Comment by spwin** [comment]
InvalidArgumentException in YamlFileLoader.php line 399:
````
There is no extension able to load the configuration for "fos_rest.view_handler" (in /Resources/config/services.yml). Looked for namespace "fos_rest.view_handler", found none
````

**Comment by jpillias** [comment]
Did you try my trick ?

**Comment by spwin** [comment]
This is result of the trick :) 
I can get it to work only if I change rest-bundle controller FOSRestController.php
````
$this->viewhandler = $this->container->get('fos_rest.view_handler');
````
to
````
$this->viewhandler = $this->container->get('fos_rest.view_handler.default');
````
manually

**Comment by jpillias** [comment]
I've just add this "trick" in app/config/service.yml at the top of the document, and don't have any problem.

**Comment by xabbuh** [comment]
Well, in fact you must nest it under the `services` key:

```yaml
services:
  fos_rest.view_handler:
    alias: fos_rest.view_handler.default
```
