### ISSUE TITLE
Force JSON responses for everything

### ISSUE THREAD

**Issue by christhomas** [FriendsOfSymfony/FOSRestBundle#1689]
Hi,

I want to provide a JSON only api and I want to never return anything that is not json.

if a 500 error hits the page the response is in text, how can I tell the fosrestbundle to ONLY output json responses and to catch all the other responses and format them the same way.

even if the accept header is sent, I Want to ignore it and send back only json.

I tried to look in the docs for a list of all the parameters and a textual explanation of what they do, but there is no documented resource.

Anybody know how to do this?

**Comment by NikitaKharkov** [comment]
Do you have such strings at config.yml?
```
fos_rest:
   ...
   format_listener:
        rules:
            - { priorities: ['json'], fallback_format: json, prefer_extension: false }
    view:
        view_response_listener: 'force'
        formats:
            json: true
   ...
```
They only do not catch errors on start kernel level. All others errors come with such format:
```
{
      "code": 400
      "message": "[problem message]"
}
```
