### ISSUE TITLE
Versioning: How to map Route Prefix to Version Listener

### ISSUE THREAD

**Issue by winkelsdorf** [FriendsOfSymfony/FOSRestBundle#1691]
Hi,

new to Symfony and FOSRestBundle, I am curious if there is an easy way to "map" a route prefix for a versioned URI to the Version Listener?

Considering the following example setup:

**config.xml**
```yaml
fos_rest:
    param_fetcher_listener: force # map all configured query parameters to request attributes
    versioning:
        enabled: true
        default_version: latest
```

**routing.yml**
```yaml
api_with_prefix:
    type:         rest
    prefix:       /{version}
#    requirements:
#        version:  latest|v1|v2
    name_prefix:  api_
    resource:     ApiBundle\Controller\ProductsController
```

**ProductsController.php**
```php
<?php

namespace ApiBundle\Controller;

use FOS\RestBundle\Controller\Annotations\RouteResource;
use FOS\RestBundle\Controller\Annotations\Version;
use FOS\RestBundle\Controller\FOSRestController;

/**
 * Class ProductsController
 * @RouteResource("Product")
 * @Version({"v1", "v2", "latest"})
 */
class ProductsController extends FOSRestController
{
    /**
     * c stands for Collection
     * /products
     * @return string
     */
    public function cgetAction()
    {
        $apiversion = $this->get('fos_rest.versioning.listener')->getVersion();
        return $apiversion;
   }
}
```

The route works when specifying an `Accept Header` or `Request Parameter` manually, the output equals the given version.

Of course the Versioning Listener does not take into account what the `URI` prefix is.

But from the docs there seems to be a way when dealing with `Path` instead of `Prefix`:
http://symfony.com/doc/master/bundles/FOSRestBundle/versioning.html#uri-api-versioning

> Note: this will override the version attribute of the request if you use the FOSRestBundle versioning.

I already searched on SO, the open & closed Issue on FOSRestBundle and Symfony 3, even some commits where parts of the docs were removed.

Can anybody point me into the right direction to support URI API Versioning, too?

Edit: Probably related to #1529?

Cheers,
Frederik
