### ISSUE TITLE
Unable to match route when using versioning and RouteResource options

### ISSUE THREAD

**Issue by pritisolanki** [FriendsOfSymfony/FOSRestBundle#1718]
Hi,

I am trying to setup a api development set up and trying to integrate FOSRest Bundle and unable to match the route. 
Symfony version : 3.1

config.yml

```
fos_rest:
    body_listener: true
    versioning:
        enabled: true
        resolvers:
            query: 
                enabled: true
                parameter_name: version
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
```

My Controller
```
namespace AppBundle\Controller;

use FOS\RestBundle\Controller\FOSRestController;
use FOS\RestBundle\Controller\Annotations\Version;
use FOS\RestBundle\Controller\Annotations\RouteResource;
use Symfony\Component\HttpFoundation\Request;

/**
 * @RouteResource("My")
 * @Version("v1")
 */

class MyController extends FOSRestController
{

    public function getAction(Request $request)
    {
        $data = "check check";
        return new JsonResponse($data);
    }
}
```
AppBundle\Resources\config\api-routing.yml

```
my:
    type: rest
    resource: "@AppBundle/Controller/MyController.php"
```
```
app\config\routing.yml
app:
    type: rest
    prefix: /
    resource: '@AppBundle/Resources/config/api-routing.yml'
```

http://127.0.0.1:8000/v1/app/my.json - no route found
http://127.0.0.1:8000/v1/app/my - no route

**Comment by ebeem** [comment]
I always feel more comfortable with the annotation, try this

```
my:
    type: annotation
    prefix: /my
    resource: "@AppBundle/Controller/MyController.php"
```

```

namespace AppBundle\Controller;

use FOS\RestBundle\Controller\FOSRestController;
use FOS\RestBundle\Controller\Annotations\Version;
use FOS\RestBundle\Controller\Annotations\RouteResource;
use Symfony\Component\HttpFoundation\Request;

class MyController extends FOSRestController
{
    /**
     * @View
     * @Route("/test", name="check_action")
     * @Method("GET")
     */
    public function getAction(Request $request)
    {
        $data = "check check";
        return new JsonResponse($data);
    }
}

```

since u did the prefix, now this function's url will be
`http://127.0.0.1:8000/my/test`

if you want to include a version number, then include the prefix as well, I would recommend you do it this way

```
app\config\routing.yml
app:
    type: rest
    prefix: /v1
    resource: '@AppBundle/Resources/config/api-routing.yml'
```

then the new url will be 
`http://127.0.0.1:8000/v1/my/test`
