### ISSUE TITLE
config format_listener->rules with attributes param leads to 406 on SF2.8 and FOSRest 2.0

### ISSUE THREAD

**Issue by mikelohmann** [FriendsOfSymfony/FOSRestBundle#1729]
I am currently migrating from FOSRest 1.3 to 2.0 using an underlying SF2.8.
If I am using the attributes parameter in the format_lister->rules section the SF RequestMatcher tries to compare the attribute's value to a request attribute, cannot find the pattern and returns false.

```yaml
# config.yml
format_listener:
        rules:
             - { path: ^/v1, priorities: [ 'json', 'xls', 'pdf', 'html' ], fallback_format: 'json', attributes: { _controller: FOS\RestBundle\Controller\ExceptionController }, prefer_extension: false }
```

This calls the RequestMatcher::matches() and then continues until all rules are finished. At the end no $format is defined what then causes the FormatListener to `throw new NotAcceptableHttpException('No matching accepted Response format could be determined');`

```php
# FormatListener-  Line 60ff
$accept = $this->formatNegotiator->getBest('');
```

```php
# FormatNegotiator - Line 57ff
foreach ($this->map as $elements) {
            // Check if the current RequestMatcherInterface matches the current request
            if (!$elements[0]->matches($request)) {
                continue;
            }
...
```

```php
# RequestMatcher - Line 156ff
    foreach ($this->attributes as $key => $pattern) {
            if (!preg_match('{'.$pattern.'}', $request->attributes->get($key))) {
                return false;
            }
     }
```

If I remove the attributes param from config.yml everything works fine. Does anyone have an idea what to change?
