### ISSUE TITLE
Exception normalizers do not work

### ISSUE THREAD

**Issue by miholeus** [FriendsOfSymfony/FOSRestBundle#1757]
I'm using version `2.2.0`.
I've created normalizer
```
# services.yml

    api.exception_normalizer:
        class: ApiBundle\Normalizer\ExceptionNormalizer
        public: false
        tags: [serializer.normalizer]
```

```
// ExceptionNormalizer.php
<?php
namespace ApiBundle\Normalizer;

use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class ExceptionNormalizer implements NormalizerInterface
{
    public function normalize($object, $format = null, array $context = array())
    {
        return array('status_code' => 'foo');
    }

    public function supportsNormalization($data, $format = null)
    {
        return $data instanceof \Exception;
    }
}
?>
```

I invoke exception in my controller
```
public function fooAction()
{
    throw new \RuntimeException("bar");
}
```

And normalizer is not invoked. I'm getting the default `fosrestbundle` exception. What am I doing wrong?

**Comment by gabma** [comment]
Make sure you declare your service like this 

```
api.exception_normalizer:
        class: ApiBundle\Serializer\ExceptionWrapperHandler
        tags:
            - { name: serializer.normalizer }
        arguments: ["@fos_rest.exception.messages_map", false]
```

ApiBundle/Serialize/ExceptionWrapperHandler.php

```
namespace ApiBundle\Serializer;

use FOS\RestBundle\Serializer\Normalizer\ExceptionNormalizer;


class ExceptionWrapperHandler extends ExceptionNormalizer
{
    /**
     * {@inheritdoc}
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $data = [];

        if (isset($context['template_data']['status_code'])) {
            $data['my_code'] = $statusCode = $context['template_data']['status_code'];
        }

        $data['my_message'] = $this->getExceptionMessage($object, isset($statusCode) ? $statusCode : null);

        return $data;
    }

    /**
     * {@inheritdoc}
     */
    public function supportsNormalization($data, $format = null)
    {
        return $data instanceof \Exception;
    }
}
```

and  config.yml
```
    exception:
        enabled: true
```
