### ISSUE TITLE
Problem with working directory in Symfony Flex

### ISSUE THREAD

**Issue by tomaszhanc** [FriendsOfSymfony/FOSRestBundle#1775]
I'm trying to play with a Symfony Flex and have a problem with RouteLoader. My configuration for a routing:
````yaml
controllers:
    resource: '../src/Controller'
    type: rest
````

Everything is OK in the browser and when I run console from bin directory. But when running console from the root directory (bin/console) there is a problem with a loader. The reason is a different working directory and DirectoryRouteLoader returns false for:

````php
return is_dir($resource);
````

For non-flex Symfony is working, because there is a different notation for a resource (bundle-notation).
