### ISSUE TITLE
How to add my own DecoderInterface?

### ISSUE THREAD

**Issue by Spider84** [FriendsOfSymfony/FOSRestBundle#1778]
Hello! I want to implement my DecoderInterface but I don't know how to "connect" my class to Rest.
As I understand I must define my decoder in config.yml:
```
fos_rest:
    body_listener:
        enabled: true
        decoders:
            mango: decoder_mango
```
But where definition of decoder_mango class? How? Help, pls.
