### ISSUE TITLE
The bundle should not override the other controller

### ISSUE THREAD

**Issue by soullivaneuh** [FriendsOfSymfony/FOSRestBundle#1784]
Currently, I have the service argument issue, related to #1733, with this:

```php
namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    /**
     * @Route("/", name="homepage")
     *
     * @return Response
     */
    public function indexAction(LoggerInterface $logger)
    {
        dump($logger);
    }
}
```

But this controller is not a rest controller and should not be managed by fos_rest services AFAIK.

Maybe I missing something on the configuration, but I can't find my need.

Here if my configuration:

```yaml
fos_rest:
    routing_loader:
        default_format: json
    body_converter:
        enabled: false
        validate: true
    serializer:
        serialize_null: true
    view:
        formats:
            xml:  false
            json: true
            rss:  false
            yml:  true
        view_response_listener: force
    param_fetcher_listener: force
    format_listener:
        rules:
            - { path: '^/api/', priorities: ['json', 'yml'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true } # FOSRest should not handle other routes than API
    versioning:
        enabled: true
        resolvers:
            media_type:
                enabled: true
```

And the routing:

```yaml
api:
    type:     rest
    resource: routing_rest.yml
    prefix:   /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
```

IMHO, routes without `rest` type should not be handled by the bundle.
