### ISSUE TITLE
Using NoRoute() Annotation Creates An Unwanted Route

### ISSUE THREAD

**Issue by brooksvb** [FriendsOfSymfony/FOSRestBundle#1789]
I want to override the default route naming scheme in a couple instances. When I use the `@Rest\NoRoute()` annotation, it oddly creates these unwanted duplicate routes:

Routes Before Adding `NoRoute()`:
```
app_systems_get:
  Method: GET
  Path: /systems/{system_name}
app_systems_new:
  Method: GET 
  Path: /systems/newsystem
get_system:
  Method: GET
  Path: /systems/{system_name}
new_system:
  Method: GET
  Path: /systems/newsystem
```

Routes After Adding `NoRoute()`:
```
app_systems_get:
  Method: ANY 
  Path: /
app_systems_get_1:
  Method: GET 
  Path: /systems/{system_name}
app_systems_new:
  Method: ANY
  PATH: /
app_systems_new_1:
  Method: GET
  Path: /systems/newsystem
```

Related Controllers:
```
/**
     * View a single system by system name.
     *
     * // @Rest\NoRoute()
     * @Rest\Get("/systems/{system_name}")
     * @internal param $system_name
     *
     * @ApiDoc(
     *     description="View a single system by system name.",
     *     statusCodes={200 = "System found.", 404 = "System not found by name."},
     *     responseMap={200 = "AppBundle\Entity\System", 404 = ""}
     * )
     *
     * Populate the $system parameter with a System object. "mapping" will use the findOneBy method, searching by
     * "name" using the "system_name" route parameter as the value. If a system is not found, the default value of null
     * in the function parameter definition will take effect.
     * @ParamConverter("system", class="AppBundle:System", options={"mapping": {"system_name": "name"}})
     *
     */
    public function getAction(Request $request, System $system = null) { ... }

/**
     * // @Rest\NoRoute()
     * @Rest\Get("/systems/newsystem")
     *
     * @ApiDoc(
     *     description="Create a new system.",
     *     input={"class"="AppBundle\Form\SystemType", "paramType" = "json"},
     *     statusCodes={
     *     201 = "System created.",
     *     400 = "Invalid data submitted. Please check for validation errors.",
     *     409 = "System already exists."}
     * )
     *
     */
    public function newAction(Request $request) { ... }
```

My initial reason for wanting to override the default route for getAction is because without the override, the generated route will falsely name the route parameter as `{system}` because of my TypeHinted function parameter. An interesting thing to note is that when I override the getAction route, although there are two duplicate routes, they both have the proper route parameter name of `{system_name}`.

My reason for overriding the newAction route is because `/systems/new` is conflicting with the getAction route and being caught by it. I overrode the route as a bandaid fix while trying to figure out how all this works.

If you have suggestions or advice or how to properly handle those two reasons, I would appreciate it, but regardless, there seems to be an issue with `NoRoute()`.
