### ISSUE TITLE
[Symfony 3.4] Issue with yaml routes

### ISSUE THREAD

**Issue by kunicmarko20** [FriendsOfSymfony/FOSRestBundle#1804]
Symfony 3.4 + Symfony Flex, when defining Controller route in `yaml` file I get an error:

> Class could not be determined for Controller identified by "routes_api_v1.yaml" in routes_api_v1.yaml (which is being imported from "/Use
  rs/markokunic/Sites/flex/config/routes.yaml"). Make sure there is a loader supporting the "rest" type.

but if I define routes with Annotation it is working.

```
# config/routes.yaml
api_v1:
    resource: "routes_api_v1.yaml"
    type: rest
    prefix: /v1
```
```
# config/routes_api_v1.yaml
api_users_get:
    path: /users/{id}
    defaults: { _controller: 'App:Test:getAction' }
    methods: [GET]
```
```
# config/routes/annotations.yaml
controllers:
    resource: ../src/Controller/
    type: annotation
```
```
# config/packages/fos_rest.yaml
fos_rest:
    versioning: true
    body_listener: true
    routing_loader:
        include_format: false
    format_listener:
        rules:
            - { path: '^/v1/', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
    param_fetcher_listener: true
    view:
        view_response_listener: force
        formats:
            json: true
        templating_formats:
            html: true
    serializer:
        serialize_null: true
```
```
# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DataFixtures,Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
```
```
<?php

namespace App\Controller;

use FOS\RestBundle\View\View;
use Symfony\Component\HttpFoundation\Response;
use FOS\RestBundle\Controller\FOSRestController;

class TestController extends FOSRestController
{
    public function getAction($id)
    {
        return View::create(['test' => ['test']],
            Response::HTTP_OK
        );
    }
}
```
```
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "RC",
    "require": {
        "php": "^7.0.8",
        "friendsofsymfony/rest-bundle": "^2.3@dev",
        "jms/serializer": "^1.9",
        "jms/serializer-bundle": "^2.2",
        "sensio/framework-extra-bundle": "^5.0",
        "symfony/console": "^3.4",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^3.4",
        "symfony/lts": "^3",
        "symfony/stopwatch": "^3.4",
        "symfony/templating": "^3.4",
        "symfony/twig-bundle": "^3.4",
        "symfony/yaml": "^3.4"
    }
```

I did not have time to deal with this so I downgraded to Symfony 3.3, just posting it here so you are aware.
