### ISSUE TITLE
JMSFormErrorHandlerPass disables overwriting class parameter jms_serializer.form_error_handler.class

### ISSUE THREAD

**Issue by GijsL** [FriendsOfSymfony/FOSRestBundle#1806]
In #1742 the JMSFormErrorHandlerPass forces the `jms_serializer.form_error_handler.class` to the one from this bundle. I previously have overwritten this parameters with my own hander:
``` yaml
parameters:
    jms_serializer.form_error_handler.class: 'MyBundle\Serializer\Handler\FormErrorHandler'
```
This is now ignored/overruled by the CompilerPass.

You can fix it by completely overwriting the service definition:
``` yaml
services:
    jms_serializer.form_error_handler:
        class: 'MyBundle\Serializer\Handler\FormErrorHandler'
        arguments: ['@translator']
        tags: [{ name: 'jms_serializer.subscribing_handler' }]
```
Or write your own CompilerPass, but that seems a bit too much. 

Is this considered to be a BC break? And should we change the implementation of the compiler pass to first check if the parameter is set to the default value of JMS, and only then overwrite it?

I can create a PR for this solution and Im also open to other suggestions.
