### ISSUE TITLE
Automatic routes should ignore autowired services

### ISSUE THREAD

**Issue by xorik** [FriendsOfSymfony/FOSRestBundle#1807]
I have an action:
```php
class ItemsController extends FOSRestController implements ClassResourceInterface
{
    /**
     * @Rest\QueryParam(name="offset", requirements="\d+", default="0")
     * @Rest\QueryParam(name="limit", requirements="\d+", default="10")
     */
    public function cgetAction(ParamFetcher $paramFetcher)
    ...
```

So I get auto-generated route. No issues here:
```
cget_items                 GET      ANY      ANY    /api/items
```

Now I want to add an auto-wired service (because now it's recommended way):
```php
public function cgetAction(ParamFetcher $paramFetcher, ItemRepository $repository)
```

Now route is broken:
```
cget_items                 GET      ANY      ANY    /api/items/{repository}
```

So I have to add an annotation as a workaround: `@Rest\Get("/items")`. Same happened for the `POST` action.

It would be great if the route-generator can detect these services and skip them.

My config:
```yaml
fos_rest:
    param_fetcher_listener:  true
    routing_loader:
        default_format: json
        include_format: false

```

Thank you
