### ISSUE TITLE
declare type rest for all the controllers

### ISSUE THREAD

**Issue by adityarai** [FriendsOfSymfony/FOSRestBundle#1811]
How to declare type: rest for annotation as shown in in routing.yml for all the controllers at once

In yml format, it is written as

```
users:
    type: rest
    resource: RestAPI\DemoBundle\Controller\UsersController
```
But for all the controllers in annotation format?
```
rest:
    resource: "@RestBundle/Controller/"
    type:     annotation
```

**Comment by xabbuh** [comment]
```yaml
rest:
    resource: '@RestBundle/Controller'
    type: rest
```

Did you try something like this?
