### ISSUE TITLE
 [Symfony 3.4] Issue with The "fos_rest.view_handler" service is private

### ISSUE THREAD

**Issue by 6ecuk** [FriendsOfSymfony/FOSRestBundle#1816]
Good day. I have in my project the message "The "fos_rest.view_handler" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0."
FOSRestBundle version: 2.3.0
Config:
```
fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    format_listener:
        rules:
          - { path: ^/, priorities: [ json ], fallback_format: json, prefer_extension: true }
```
