### ISSUE TITLE
FosRestBundle doesn't hide exceptions messages

### ISSUE THREAD

**Issue by aoudjehih** [FriendsOfSymfony/FOSRestBundle#1821]
Hi,

With this config below, I can't hide messages exceptions and show only those that I want to show :
``` yml
fos_rest:
    body_converter:
        enabled: true
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: force
    serializer:
        serialize_null: true
    param_fetcher_listener: force
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }
    exception:
        enabled: true
        codes:
           'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException': 405
           'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
        messages:
           'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
``` 

the aim is to keep only the status code for MethodNotAllowedHttpException, but all the time I have the message, event if I add in messages: 

``` yml
       messages:
           'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
           'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException': false
```
