### ISSUE TITLE
[SF4] Annotations seems to not works

### ISSUE THREAD

**Issue by emulienfou** [FriendsOfSymfony/FOSRestBundle#1826]
Hello, trying to work with FOSRestBundle, but having some troubles using annotations to add **prefix** for route.

Here is my `fos_rest.yaml` file looks like:
```yaml
fos_rest:
  body_listener: true
  routing_loader: true
  versioning:
    enabled: true
    resolvers:
      query: true
  format_listener:
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
  param_fetcher_listener: true
  view:
    view_response_listener: 'force'
    formats:
      json: true
```

Here is my user controller:
```php
/**
 * Class UserController
 * @Rest\Route(host="api.%domain%")
 * @Rest\Prefix("/users")
 *
 * @package ProjectHarmony\Rest
 */
class UserController extends FOSRestController
{

    /**
     * Check Access Token exists in database.
     * @QueryParam(name="accessToken")
     * @Rest\Get("/token-status")
     *
     * @param ParamFetcherInterface $paramFetcher
     *
     * @return array
     */
    public function getTokenStatusAction(ParamFetcherInterface $paramFetcher): array
    {
        $accessToken = $paramFetcher->get('accessToken');

        return [
            'status' => null !==
                $this->getDoctrine()->getRepository(User::class)->findOneBy(['apiToken' => $accessToken])
        ];
    }
}
```

Running the next command:
> php bin/console debug:router

I got:
>   projectharmony_rest_user_gettokenstatus GET ANY api.harmonycms.net /token-status

However the route should be: **/users/token-status**.

Thanks for your help !!!

**Comment by Oviglo** [comment]
+1

**Comment by emulienfou** [comment]
Hi @Tobion,
after some tests a long time ago, it seems the annotation `@Rest\Prefix("/user")` do nothing, however using the `@Rest\Route("/user", host="api.%domain%")` add successfully the prefix `/user`.

Here is how I load my routes:
```yaml
# REST API
rests:
  resource: ../../src/Rest/
  type: annotation
```
