### ISSUE TITLE
error message: Unexpected '<' on exception enable 

### ISSUE THREAD

**Issue by rcsofttech85** [FriendsOfSymfony/FOSRestBundle#1839]
hi, i am using symfony 4 and this is my fos_rest.config file.

```yaml
fos_rest:
  body_listener: true
  routing_loader:
     default_format: json
     include_format: false
  versioning:
    enabled: true
    resolvers:
      query: true
  format_listener:
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
  body_converter:
    enabled: true
    validate: true
  param_fetcher_listener: true
  exception:
    enabled: true
  view:
    view_response_listener: 'force'
    formats:
      json: true
```

when fos_rest.exception.enabled is set to true, i am getting an unexpected  '<'  , please let me know how to fix this.
