### ISSUE TITLE
Error : "You must enable the SensioFrameworkExtraBundle view annotations"

### ISSUE THREAD

**Issue by LMO-NEO** [FriendsOfSymfony/FOSRestBundle#1846]
Hello,

I use Symfony 2.8 with FOSRestBundle 1.8, (i can't update, this is fixed because i am in a collab work).

I have this error when i call a controller method that returns a view Response (by View::create($data)) : 
RuntimeException in ConfigurationCheckPass.php line 34:
You must enable the SensioFrameworkExtraBundle view annotations to use the ViewResponseListener.

I read all issues concerning configuration of the bundle and problems with FrameworkExtraBundle, but no solution work for me ...

In my config.yml file, i have : 

```yaml
# fos_rest configuration
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
    routing_loader:
        default_format: json
        include_format: false
sensio_framework_extra:
    view: { annotations: false }
```

Thanks for your help :)
