### ISSUE TITLE
Unable to find template "" 

### ISSUE THREAD

**Issue by rcsofttech85** [FriendsOfSymfony/FOSRestBundle#1853]
Hi, 
help me to fix this issue.
The written code is working fine for rest endpoint and throws proper exception code when i access a non-existence rest end point . It also loads html correctly for regular symfony routes if exists. 
now the problem occurs when i access a non existence symfony route[not rest] , expected result was not found but received Unable to find template "" 

here is my config file:

```yaml
fos_rest:
    body_listener: true
    body_converter:
       enabled: true
       validate: true
       validation_errors_argument: validationErrors
    param_fetcher_listener: true
    routing_loader:
       default_format: json
       include_format: false
    format_listener:
      rules:
          - { path: '^/api', priorities: [ 'json'], fallback_format: json , prefer_extension: true }
          - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: false }
    exception:
        enabled: true
       exception_controller: 'App\Exception\ExceptionController::showAction'
    view:
       view_response_listener: 'force'
    serializer:
       groups: ['Default']
```

I am using symfony4

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by rcsofttech85** [comment]
https://github.com/rcsofttech85/fos

**Comment by Kafei59** [comment]
I exactly have the same issue, after requiring and setting twig as template engine for fosrest.

For informations, I had to require fosrest as dev-master to handle an issue on public services (it was not able to inject view_handler service because of its private state: https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1790) and force the installation of twig for an API skeleton to handle the issue: 
An instance of Symfony\Bundle\FrameworkBundle\Templating\EngineInterface must be injected in FOS\RestBundle\View\ViewHandler

And now, I also have this issue on unable to find a template "".
By the way, it's not possible to used fosrest without requiring twig ? I mean, this project will only serve json responses so it's useless to instantiate the whole twig engine just for that.

PS: here is my configuration

config/packages/fos_rest.yml
```yaml
fos_rest:
    body_listener: true
    param_fetcher_listener: true
    routing_loader: true
    view:
        view_response_listener: 'force'
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
```

config/packages/framework.yml
```yaml
framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: ~

    php_errors:
        log: true

    templating: { engines: ['twig'] }

sensio_framework_extra:
    view: { annotations: true }
```
