### ISSUE TITLE
Config include_format: false not working

### ISSUE THREAD

**Issue by fefas** [FriendsOfSymfony/FOSRestBundle#1868]
Hello there,

I'm having an issue regarding using extension on the URL (`GET sample.com/resources/<code>.json`). I guess something is wrong on my configs 😄 ..

The controller looks like this:
```php
<?php

namespace App\Controller;

use FOS\RestBundle\Controller\FOSRestController;
use FOS\RestBundle\Controller\Annotations as Rest;
use App\Resource;

class ResourceController extends FOSRestController
{
    /**
     * @Rest\Get("/resources/{code}", name="get_resource")
     */
    public function getResource(string $code)
    {
        $resource = new Resource($code);

        $view = $this->view($resource, 200);

        return $this->handleView($view);
    }
}
```

The output for requesting using `GET sample.com/resources/BLA.json` is:
```json
{
    "code": "BLA.json"
}
```

**Problem:** the format extension `.json` is sent with the argument to the controller.

We have Symfony 4 here and the `fos_rest.yml` config is:
```yaml
fos_rest:
    exception:
        enabled: true
    routing_loader:
        include_format: false
    format_listener:
        enabled: true
        rules:
            - path: ^/
              prefer_extension: true
              fallback_format: null
              priorities: [json, xml]
```

I've searched a lot on docs and old issues and the entry `include_format: false` should solve it, but not ..

Could someone please help me?
