### ISSUE TITLE
Symfony4 JMS return empty JSON

### ISSUE THREAD

**Issue by Oviglo** [FriendsOfSymfony/FOSRestBundle#1871]
Hello,
I installed JMSSerializer but when I return entities in JSON the response is empty. This is my config:

```yaml
fos_rest:
    body_listener: true
    body_converter:
        enabled: true
    service:
        view_handler: tigris_base.view_handler
        serializer: fos_rest.serializer.jms
    view:
        default_engine: twig
        view_response_listener: force
        formats:
            json: true
            pdf: true
            xls: true
            html: false
        templating_formats:
            pdf: false
            xls: false
            json: false
            html: true
    serializer:
        serialize_null: true
    routing_loader:
        default_format: html
        prefix_methods: false
    param_fetcher_listener: true
    allowed_methods_listener: true
```

Can you have this issue with Symfony4 ?
Thanks.
