### ISSUE TITLE
Trailing slash added to the URL when actions are split into Controllers

### ISSUE THREAD

**Issue by grzegorztomasiak** [FriendsOfSymfony/FOSRestBundle#1886]
Using `FOSRestBundle 2.3.1`

So given the following example:

Directory
```
Controllers/Api/
    - Clients/
        - GetAction/
              - ClientsGetController.php
        - PostAction/
              - ClientsPostController.php
```

routing.yml

```yml
api.clients.get:
  type: rest
  resource: "@AppBundle/Controller/Api/Clients/GetAction/ClientsGetController"
  name_prefix: api.clients__
  prefix: /clients
  options:
    expose: true

api.clients.post:
  type: rest
  resource: "@AppBundle/Controller/Api/Clients/PostAction/ClientsPostController"
  name_prefix: api.clients__
  prefix: /clients
  options:
    expose: true
```

ClientsGetController.php

```php
<?php declare(strict_types=1);

...

class ClientsGetController extends RestController
{
    /**
     * @Rest\Get()
     */
    public function getAction(Request $request):View
    {
        ...
    }
}
```

ClientsPostController.php

```php
<?php declare(strict_types=1);

...

class ClientsPostController extends RestController
{
    /**
     * @Rest\Post()
     */
    public function postAction(Request $request):View
    {
        ...
    }
}
```

Results with the following API endpoints:

```yml
api.clients__custom GET /api/clients/custom # note that this endpoint is not in the above's example
api.clients__get GET /api/clients/
api.clients__post POST /api/clients/
```

Everything works fine except that the trailing slash is added to the URL and obviously the endpoint won't work without the slash at the end. I know I can make redirection from / to none however it's not a desired solution.

Additionally:
Seems like global `prefix_methods` is ignored, because when set to false it still adds method names to the route, this is why I need to have

```yml
api.clients.post:
  type: rest
  ...
  name_prefix: api.clients.
  ...
```

instead of

```yml
api.clients.post:
  type: rest
  ...
  name_prefix: api.clients.post
  ...
```
Any idea?
