### ISSUE TITLE
rest annotation issue with symfony 4

### ISSUE THREAD

**Issue by aayaresko** [FriendsOfSymfony/FOSRestBundle#1889]
hello. first of all, thanks  a lot for this useful extension. it's very handy.
somehow symfony does not see rest annotations:

here is my config/routes/annotations.yaml
````
controllers:
    resource: ../../src/Controller/Mixed
    type: annotation

api:
    resource: ../../src/Controller/API
    type: rest
    prefix: /api/v1/
````
here is my example controller
````
<?php

namespace App\Controller\API;

use App\Entity\PlayList\PlayList;
use FOS\RestBundle\Controller\Annotations as Rest;
use Symfony\Component\HttpFoundation\Response;

/**
 * Class UserPlayListController.
 *
 * @Rest\NamePrefix("api.user.play_list.")
 * @Rest\Prefix("user/play-list")
 * @package App\Controller
 */
class PlayListController extends ApiController
{
    /**
     * @Rest\Get("/")
     */
    public function index()
    {
        $em         = $this->getDoctrine();
        $repository = $em->getRepository(PlayList::class);
        $entities   = $repository->findByUser($this->getUser());
        $view       = $this
            ->view(
                $entities,
                Response::HTTP_OK,
                [
                    'view_default',
                ]
            );

        return $this->handleView($view);
    }
}
````

and bin/console debug:controller does not show the route.

thanks in advance.
