### ISSUE TITLE
Using Controller subdirectory for Routing Resource

### ISSUE THREAD

**Issue by leek** [FriendsOfSymfony/FOSRestBundle#189]
I am attempting to load all controllers under a subdirectory as `type: rest` in my Route configuration similar to how it is done in the `SensioFrameworkExtraBundle` [here](http://symfony.com/doc/2.0/bundles/SensioFrameworkExtraBundle/annotations/routing.html#activation):

```yml
# routing.yml

foobar_api:
    resource: "@PWFoobarBundle/Controller/Api/"
    type:     rest
```

Is anything like this possible? Is there another way of setting up routes from within a subdirectory of `Controller/`? I've tried any syntax I could think of, even down to specifying individual controller classes within the subdirectory and none seem to work.

**Comment by Soullivaneuh** [comment]
Great :+1: for this.

Having this kind of configuration:

```yaml
api:
    type:     rest
    resource: "@AppBundle/Controller/"
    prefix:   /api
```

Would be very painless than defined a resource per controller, especially for huge API.
