### ISSUE TITLE
Override ViewHandler

### ISSUE THREAD

**Issue by emulienfou** [FriendsOfSymfony/FOSRestBundle#1913]
Hello there,
I'm using **FOSCommentBundle** under **Symfony 4.1** who use **FOSRestBundle** and I'm trying to override the `FOS\RestBundle\View\ViewHandler` class.   
However I think there is something missing because I've got the next error: `Format 'html' not supported, handler must be implemented`!

Here is my class:
```php
<?php
namespace Acme\Rest;
class ViewHandler extends \FOS\RestBundle\View\ViewHandler { }
```

And here is my service declaration:
```yaml
Acme\Rest\ViewHandler:
    arguments: ['@fos_rest.router', '@fos_rest.serializer', '@?fos_rest.templating', '@request_stack']
    public: true
```

And calling my service like:
```php
$this->container->get('Acme\Rest\ViewHandler');
```

However, when I use the service `fos_rest.view_handler`, I do not have this issue, only when using my own service!

Did I need to do something else when declaring my service?

Thanks
