### ISSUE TITLE
Handle FOSRestBundle with JMSSerializer and POST params

### ISSUE THREAD

**Issue by suiXz** [FriendsOfSymfony/FOSRestBundle#1956]
Hi guys !

I'm trying to transform json post param in my API to Doctrine entity with this bundle : 

Here's my controller :

```php
//\Ve\DelcoBundle\Controller\PsServiceController.php
/**
 * Class PsServiceConroller
 * @package Ve\DelcoBundle\Controller
 */
class PsServiceController extends FOSRestController
{
    /**
     * @param Article $article
     *
     * @return Response
     * @Rest\Post("/article")
     * @Rest\View(StatusCode = 201)
     * @ParamConverter("article", converter="fos_rest.request_body")
     */
    public function postArticle(Article $article)
    {
        try {
            $p = 'plop';
            $em = $this->getDoctrine()->getManager('crm');
            $em->persist($article);
            $articleData = $this->get('jms_serializer')->serialize($article, 'json');

            $response = new Response($articleData, Response::HTTP_FOUND);
            $response->headers->set('Content-Type', 'application/json');

            $em->flush();

        } catch (\Exception $e) {
            return new JsonResponse(['message' => 'Can\'t create Article' . $e->getMessage()], Response::HTTP_BAD_REQUEST);
        }

        return $response;
    }
}
```

My config :

```yaml
#config.yml
fos_rest:
    routing_loader:
        include_format: false
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    body_converter:
        enabled: true
        validate: true
    view:
        formats: { json: true, xml: false, rss: false }
    serializer:
        serialize_null: false
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }
    zone:
        - { path: ^/api/* }
```

And there you can see my  boyd from the post request (for postArticle) : 

```json
{
	"code": "ECOGREEN_m10",
	"descriptif": "super produit",
	"designation": "designation",
	"designation_courte": "desigghjghjj",
	"photo_principale_fichier_nom": "abc",
	"famille": "famille"
}
```

My problem is there :
![image](https://user-images.githubusercontent.com/6963038/48367267-72d51580-e6b0-11e8-92b0-0784b251582d.png)

The post parameters like xxx_yyy (like designation_courte) became xxxYyy with the CamelKeysNormalizer from FOS\RestBundle. I keep the value in this one : 
```php
    public function normalize(array $data)
    {
        $this->normalizeArray($data);

        return $data;
    }
```
But when it comes in the request the value is empty (see the previous screenshot)

I'm pretty sur it's linked to JMS Serializer Bundle. But i can't change this parameter : 
```yml
#config.yml
parameters:
    locale: en
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
```

Sorry for my bad english...
