### ISSUE TITLE
Exception Controller problem

### ISSUE THREAD

**Issue by mailaneel** [FriendsOfSymfony/FOSRestBundle#208]
If the below exception is thrown, _format is not correctly set and even if request json format i am getting html format

<code> Symfony\Component\Security\Core\Exception\AuthenticationCredentialsNotFoundException </code>

Below is my configuration

``` yaml
fos_rest:
    routing_loader:
        default_format: json
    view:
        default_engine: twig
        view_response_listener: force
        formats:
            json: true
            xml: true
        templating_formats:
            html: true
    body_listener: true
    format_listener:
        default_priorities: [html,json] 
        fallback_format: json
        prefer_extension: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
            'WSL\BaseBundle\Exception\EntityNotFoundException': 200
            'Symfony\Component\Security\Core\Exception\AuthenticationCredentialsNotFoundException': 401
        messages: 
            'WSL\BaseBundle\Exception\EntityNotFoundException': true
            'Symfony\Component\Security\Core\Exception\AuthenticationCredentialsNotFoundException': true
    service:
        view_handler: fos_rest.view_handler.default  
```
