### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by enumag** [FriendsOfSymfony/FOSRestBundle#2111]
I'm trying to upgrade my project to Symfony 4.4 LTS. However even with the latest release of this bundle I'm getting this deprecation:

```
  1x: The "controller_name_converter" service is deprecated since Symfony 4.3. It is being referenced by the "fos_rest.routing.loader.controller" service.
```

I see this was already [fixed](https://github.com/FriendsOfSymfony/FOSRestBundle/commit/bc7856c9ca6a78678ca715e54909cd84cdef2f56) in master. When can we expect a release?

**Comment by xabbuh** [comment]
You can try `2.8@dev` for now and disable the controller name parser like this:

```yaml
fos_rest:
    routing_loader:
        parse_controller_name: false
```
