### ISSUE TITLE
Load route annotations from a directory

### ISSUE THREAD

**Issue by W0rma** [FriendsOfSymfony/FOSRestBundle#2132]
All of my controllers are located under `src/Controller`.

I'm searching for a way to load all routes from this directory at once.

After switching to symfony flex using the following syntax does not work anymore as the controllers are no longer part of a bundle:

```
api:
    type: rest
    resource: "@AppBundle/Controller/"
```

Is there a possibility to configure an absolute path here, f.e.

```
api:
    type: rest
    resource: "%kernel.project_dir%/src/Controller"
```

Currently this syntax does not work.

In https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1377#issuecomment-194898332 there was a small hint that it might be helpful to support this.

Do I miss something here or is it really not possible to load all routes at once?

**Comment by marmichalski** [comment]
I have my routes defined relatively and it works:
```yaml
api_controllers:
    resource: ../../src/UserInterface/Symfony/Controller/Api/
    prefix: /api
    type: annotation
```
