### ISSUE TITLE
Simultaneous usage of prefix and multiple controllers

### ISSUE THREAD

**Issue by paztek** [FriendsOfSymfony/FOSRestBundle#215]
I'm trying to implement a Restful API for admins only under the "/admin" directory.

I succeeded with one Controller, managing one type of entity but when I try with 2 Controllers and 2 entities with a parent-child relationship, the routes of the Controller of the child entity aren't correctly loaded :

Here are the related files :

``` yaml
#carte_routes.yml :
admin_categories:
    type: rest
    resource: Fastcook\CarteBundle\Controller\CategorieAdminController
admin_produits:
    type: rest
    parent: admin_categories
    resource: Fastcook\CarteBundle\Controller\ProduitAdminController
```

```
<?php
// ProduitAdminController.php
/**
 * Produits admin controller.
 * 
 * @NamePrefix("admin_carte_")
 * @Prefix("/admin/carte")
 */
class ProduitAdminController extends Controller
```

```
<?php
// CategorieAdminController.php :
/**
 * Categories admin controller.
 * 
 * @Prefix("/admin/carte")
 * @NamePrefix("admin_carte_")
 */
class CategorieAdminController extends Controller
```

But when I run router:debug, I have the following routes :

```
admin_carte_edit_categorie           GET    /admin/carte/categories/{id}/edit.{_format}
admin_carte_new_categories           GET    /admin/carte/categories/new.{_format}
admin_carte_delete_categorie         DELETE /admin/carte/categories/{id}.{_format}
admin_carte_get_categorie            GET    /admin/carte/categories/{id}.{_format}
admin_carte_get_categories           GET    /admin/carte/categories.{_format}
admin_carte_post_categories          POST   /admin/carte/categories.{_format}
admin_carte_put_categorie            PUT    /admin/carte/categories/{id}.{_format}
admin_carte_edit_categorie_produit   GET    /categories/{id}/admin/carte/produits/{id2}/edit.{_format}
admin_carte_new_categorie_produit    GET    /categories/{id}/admin/carte/produit/new.{_format}
admin_carte_delete_categorie_produit DELETE /categories/{id}/admin/carte/produits/{id2}.{_format}
admin_carte_get_categorie_produit    GET    /categories/{id}/admin/carte/produits/{id2}.{_format}
admin_carte_post_categorie_produit   POST   /categories/{id}/admin/carte/produit.{_format}
admin_carte_put_categorie_produit    PUT    /categories/{id}/admin/carte/produits/{id2}.{_format}
```

My question is "Is it possible to simultaneously use @Prefix and multiple controllers ?"
