### ISSUE TITLE
Error with Symfony 4.4

### ISSUE THREAD

**Issue by Oxygen66** [FriendsOfSymfony/FOSRestBundle#2176]
Hi team !

I have this error on Symfony upgrade to 4.4 on all my routes (profiler,  rest routes, etc):
```
Argument 2 passed to Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::__construct() must be an instance of Twig_Environment or null, instance of Twig\Environment given, called in /Users/adrien/www/myproject/var/cache/dev/ContainerYXXyrgy/srcApp_KernelDevDebugContainer.php on line 6196
```

You can find my fos_rest config below:
```yaml
fos_rest:
    view:
        view_response_listener: 'force'
        formats:
            json: true
        serialize_null: true
    serializer:
        serialize_null: true
    routing_loader:
        include_format: false
    format_listener:
        rules:
            - { path: ^/*, priorities: [ 'json' ], fallback_format: json, prefer_extension: false }
```

And if i set type: annotation on my config route, the default homepage work but not the rest.
If you have questions which can help you, ask me please because i really don't understand this error: everything worked in 4.3 :/
