### ISSUE TITLE
"Class could not be determined for Controller identified by"

### ISSUE THREAD

**Issue by codeMonkeysBe** [FriendsOfSymfony/FOSRestBundle#218]
I have the following configuration

app/config/config.yml

```
fos_rest:
    routing_loader:
        default_format: json
    view:
        default_engine: twig
        view_response_listener: force
        formats:
            json: true
            xml: true
        templating_formats:
            html: true
    body_listener: true
    format_listener:
        default_priorities: [html,json]-
        fallback_format: json
        prefer_extension: true
    service:
        view_handler: fos_rest.view_handler.default
```

routing.yml

```
on_demand_rest:
    type:     rest
    resource: TON\VideoBundle\Controller\VideoRestController
```

When loading the app I get

```
Cannot import resource "\TON\VideoBundle\Controller\VideoRestController" from "/home/niki/src/trunk/vendor/bundles/TON/Bundle/VideoBundle/Resources/config/routing_rest.yml".
500 Internal Server Error - FileLoaderLoadException
1 linked Exception: InvalidArgumentException »
```

When I follow the trace, relevant seems

```
at RestRouteLoader ->getControllerLocator ('\TON\VideoBundle\Controller\VideoRestController') 
in /home/niki/src/trunk/vendor/bundles/FOS/RestBundle/Routing/Loader/RestRouteLoader.php at line 73
```
