### ISSUE TITLE
What is the proper way to configure FOSRestBundle with Symfony 5?

### ISSUE THREAD

**Issue by grzegorztomasiak** [FriendsOfSymfony/FOSRestBundle#2241]
I put this in `routes.yml`:

```yml
api:
  type: rest
  resource: "routes_api.yml"
  prefix:   /api/v2
```

and `routes_api.yml`
```php
my_endpoint:
  path: /my-endpoint
  defaults: { _controller: App:Endpoint:my }
  methods:
    - GET
```

but I get the error:

> Cannot load resource "App\Controller\EndpointController". Make sure there is a loader supporting the "rest" type.
