### ISSUE TITLE
Unable to return csv file

### ISSUE THREAD

**Issue by pcmanprogrammeur** [FriendsOfSymfony/FOSRestBundle#2303]
Hi,
I want to return a csv file but it doesn't work.

Here is my fost_rest.yaml :

```
fos_rest:
    format_listener:
        rules:
            - { path: .*/feed.csv, prefer_extension: true, fallback_format: txt, priorities: [ txt ] }
```

But i have the error :
`Format 'txt' not supported, handler must be implemented`

Do you have any idea ?
