### ISSUE TITLE
Invalid configuration for path "fos_rest.routing_loader": only "false" is supported

### ISSUE THREAD

**Issue by martinszeltins** [FriendsOfSymfony/FOSRestBundle#2367]
I am getting this error with the default configuration.

> Invalid configuration for path "fos_rest.routing_loader": only "false" is supported

````
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader: true
    view:
        view_response_listener:  true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
````

I am using `Symfony 6.0` and `friendsofsymfony/rest-bundle 3.3`
