### ISSUE TITLE
Exceptions mapped in config aren't caught anymore, 500 is thrown instead

### ISSUE THREAD

**Issue by SebastienTediber** [FriendsOfSymfony/FOSRestBundle#2369]
Hello,

Since we updated to 3.x.x, the exceptions I mapped in my config files aren't caught and a 500 is thrown instead.

Here is my configuration :

```
fos_rest:
    exception:
        enabled: true
        messages:
            Symfony\Component\HttpKernel\Exception\HttpException: true
            InvalidArgumentException: true
            Sylius\Component\Resource\Exception\UnexpectedTypeException: true
            PHPUnit\Framework\Warning: true

    view:
        formats:
            json: true
            xml:  true
        empty_content: 204
    format_listener:
        rules:
            - { path: '^/shop-api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/api/.*', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
            - { path: '^/cron/.*', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true }
```

I have been trying with InvalidArgumentException thrown.

I have been changing the configuration a few times, adding the code to my exception too, it still does not work.

**Comment by GuillaumeTediber** [comment]
Hello
@goetas @W0rma 

Do you have any ideas in how to use fos_rest error caching functionnality for version 3.X.X ?
This would help us a lot.

Thank you,

Guillaume Bidan
CTO
Tediber

**Comment by WissameMekhilef** [comment]
Hi!

I have also been facing this issue, trying to clean up the log output to focus on what matter and having uncaught exception is making it harder.

**Comment by InjustFr** [comment]
@SebastienTediber I think your configuration needs an update. Mine is working fine, here it is (the exception part):
```yaml
fos_rest:
    exception:
        map_exception_codes: true
        codes:
            'InvalidArgumentException': 422
            'Doctrine\ORM\EntityNotFoundException': 404
        messages:
            'InvalidArgumentException': true
            'Doctrine\ORM\EntityNotFoundException': true
```

You also have to set exception_controller to null in twig.yaml, if you're using twig
