### ISSUE TITLE
Exceptions not thrown (missing info from docs?)

### ISSUE THREAD

**Issue by Bendihossan** [FriendsOfSymfony/FOSRestBundle#289]
Following the docs on [exception controller support](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Resources/doc/4-exception-controller-support.md) I've done the following:

``` yaml
#app/config/config.yml
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

fos_rest:
    routing_loader:
        default_format: null
    view:
        default_engine: twig
        force_redirects:
            html: true
        formats:
            json: true
            xml: true
        templating_formats:
            html: false
        view_response_listener: 'force'
        failed_validation: HTTP_BAD_REQUEST
    body_listener:
        decoders:
            json: fos_rest.decoder.json
            xml: fos_rest.decoder.xml
    format_listener:
        default_priorities: [json]
        fallback_format: json
        prefer_extension: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
```

And in my controller:

``` php
public function indexAction()
{
    throw new ResourceNotFoundException(404, "No route available.");
} // "index"     [GET] /
```

This returns `null` in the response (with no database configured) and the header shows `Content-Type: application/json` and the status code `200 OK`. I'm obviously missing something here, but the question is what?
