### ISSUE TITLE
Can't get ParamFetcher into controller

### ISSUE THREAD

**Issue by PoisonousJohn** [FriendsOfSymfony/FOSRestBundle#304]
I got error 

Controller "Push\PointsBundle\Controller\RestController::checkPointsAction()" requires that you provide a value for the "$paramFetcher" argument 

my config

``` yml
fos_rest:
      param_fetcher_listener: 'force'
      view:
          formats:
              json: true
              xml: false
              rss: false
          mime_types:
              json: ['application/json', 'application/x-json', 'application/vnd.example-com.foo+json']
              png: 'image/png'
          failed_validation: HTTP_BAD_REQUEST
          default_engine: twig
          view_response_listener: 'force'
      format_listener:
          default_priorities:
              - json
      routing_loader:
          default_format: json

  sensio_framework_extra:
      view:    { annotations: false }
      router:  { annotations: true }
```

controller

``` php
<?php

namespace Push\PointsBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Nelmio\ApiDocBundle\Annotation\ApiDoc;
use FOS\RestBundle\View\View;
use FOS\RestBundle\Controller\Annotations\QueryParam;
use FOS\RestBundle\Request\ParamFetcherInterface;
use FOS\RestBundle\Controller\Annotations\RequestParam;
use FOS\RestBundle\Request\ParamFetcher;

class RestController extends Controller
{
    /**
     * @QueryParam(name="latitude", requirements="[0-9.]+", default="0", description="")
     * @ApiDoc()
     */
    public function checkPointsAction(ParamFetcher $paramFetcher)
    {
        $view = new View();

        $data = array();
        $data[] = $this->getRequest()->get('latitude');
        $view->setData($data);

        return $this->get('fos_rest.view_handler')->handle($view);
    }
}
```

Also I don't see ParamFetcherListener in services:

$ php console container:debug | grep fos_res | grep listener
fos_rest.body_listener                                        container FOS\RestBundle\EventListener\BodyListener
fos_rest.format_listener                                      container FOS\RestBundle\EventListener\FormatListener
