### ISSUE TITLE
MethodNotAllowedException is not caught 

### ISSUE THREAD

**Issue by marcospassos** [FriendsOfSymfony/FOSRestBundle#358]
Hi all,

I've the following configuration:

```yml
product_option_create:
    pattern: /create.{_format}
    defaults:
        _format: ~
        _controller: colibri_product.controller.option:createAction
    requirements:
        _method: POST
```
```yml
twig:
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
```
Accessing `option/create.json`, results in:
![Untitled](https://f.cloud.github.com/assets/943036/63162/c1e76620-5dbb-11e2-8568-fc0e6fd61578.jpg)

There is some way to handle this exception properly?

I was expecting something like:
```json
{
    "status":"error",
    "status_code":405,
    "status_text":"Method Not Allowed",
    "current_content":"",
    "message":"Method Not Allowed (Allow: POST)"
}
```

Thanks in advance.

**Comment by kminh** [comment]
I'm having the exact same issue using Symfony 2.6.1 and FOSRestBundle 1.4.2.

My configuration is as followed:

```yml
fos_rest:
    access_denied_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
        mime_types:
            json: ['application/json; charset=UTF-8', 'application/json']
    routing_loader:
        default_format: json
        include_format: false
```

I doubt that I'm doing something wrong, because all I have done is setting up some empty controllers to test, using this documentation: https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Resources/doc/5-automatic-route-generation_single-restful-controller.rst

The response for a 405 response code is always a standard Symfony exception page.

I have taken a look at https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Resources/doc/4-exception-controller-support.rst too but the documentation seems outdated as there are neither `enabled` nor `exception` configuration key under `fos_rest`.

Thanks for any insight.
