### ISSUE TITLE
FOSRestBundle serves application/JSON header with HTML content in IE 10

### ISSUE THREAD

**Issue by wowpatrick** [FriendsOfSymfony/FOSRestBundle#372]
In IE10 when I request a page in IE 10, FOSRestBundle returns the HTML page but with application/JSON content type headers, resulting IE 10 to show a download flash instead of the HTML page. Chrome and Firefox work fine.

Request header in IE 10:

```
Accept: text/html, application/xhtml+xml, */*
```

Response:

```
Content-Type: application/json
```

config.yml:

```
# FOS Rest Bundle configuration:
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        default_priorities: ['html', json, '*/*']
        fallback_format: html
        prefer_extension: true
```

But the response body is the correct HTML page. Is this a problem in IE10 or the FOSRestBundle?
