### ISSUE TITLE
Wrong singular Naming conventions with parent-child routing 

### ISSUE THREAD

**Issue by sebakerckhof** [FriendsOfSymfony/FOSRestBundle#383]
I had a routing setup like this:

``` yaml
locations:
    type:     rest
    resource: SK\IsebaertBundle\Controller\LocationsController

devices:
    type:     rest
    parent:   locations
    resource: SK\IsebaertBundle\Controller\DevicesController
```

However, The LocationsController was something I adapted from the documentation (UsersController). I renamed all actions to locations, but I forgot to rename the last one, this:

``` php
    public function unlinkUserAction($slug)
    {

    } // "link_user_friend"     [UNLINK] /users/{slug}
```

However, symfony couldn't find routes for locations/{locationid}/devices

I had a look at the FosRestBundle routing classes, and found out the "collectionParents" map in "RestYamlCollectionLoader" had this entry: "locations" => "User"

This is because when the controller is processed, it thinks the singular name of the controller was "User" because of the one action I forgot to rename. 
While one could argue whether this behavior is incorrect or not, it is confusing and not what you would expect...
