### ISSUE TITLE
Routing not working in 2.2?

### ISSUE THREAD

**Issue by MichaelHindley** [FriendsOfSymfony/FOSRestBundle#385]
Hi, 
I can't seem to get routing to load with Symfony 2.2

composer.json:

``` json
 {
    "name": "symfony/framework-standard-edition",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": { "": "src/" }
    },
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.2.*",
        "php": ">=5.3.3",
        "doctrine/orm": ">=2.2.3,<2.4-dev",
        "doctrine/doctrine-bundle": "1.2.*",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "2.1.*",
        "symfony/swiftmailer-bundle": "2.2.*",
        "symfony/monolog-bundle": "2.2.*",
        "sensio/distribution-bundle": "2.2.*",
        "sensio/framework-extra-bundle": "2.2.*",
        "sensio/generator-bundle": "2.2.*",
        "jms/security-extra-bundle": "1.4.*",
        "jms/di-extra-bundle": "1.3.*",
        "jms/serializer-bundle": "0.9",
        "friendsofsymfony/user-bundle": "1.3.1",
        "friendsofsymfony/rest-bundle": "0.10.0",
        "knplabs/knp-paginator-bundle": "dev-master"

    },
    "scripts": {
        "post-install-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },
    "config": {
        "bin-dir": "bin"
    },
    "minimum-stability": "dev",
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web"
    }
}
```

routing.yml:
These do not work:

``` yaml
gateway_contact:
    type: rest
    resource: GatewayHomepageBundle\Controller\ContactController.php

gateway_contact:
    type: rest
    resource: GatewayHomepageBundle\Controller\ContactController.php

gateway_contact:
    type: rest
    resource: GatewayHomepageBundle/Controller/ContactController.php

gateway_contact: #this is how it was in 2.1 and was working without issues
    type: rest
    resource: "@GatewayHomepageBundle/Controller/ContactController.php"
```

Controller:

``` php
namespace Gateway\HomepageBundle\Controller;

use Symfony\Component\HttpFoundation\Response;

use FOS\RestBundle\Controller\FOSRestController;
use FOS\RestBundle\View\View;

use Gateway\HomepageBundle\Form\ContactType;
use Gateway\HomepageBundle\Entity\Contact as Contact;


class ContactController extends FOSRestController {
....

    public function postContactAction()
    {
        return $this->processForm(new Contact(), new ContactType());
    }
}
```

The error is:

An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "post_contact" as such route does not exist.") 

(sorry for bad formatting, don't really get how it works on github, but its not html tags :p)
