### ISSUE TITLE
getting Serializer::SetVersion() undefined when defining versions with $view->setSerializationVersion() + problem with exclusion policy?

### ISSUE THREAD

**Issue by arashdalir** [FriendsOfSymfony/FOSRestBundle#386]
I'm defining a RESTful bundle for a project. I've defined the property versions according to the documentations found here: (http://jmsyst.com/libs/serializer/master/reference/yml_reference)

and this is the result:

``` yaml
My\UserBundle\Model\User:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            since_version: 1.0
            expose: true
        username:
            since_version: 1.0
            expose: true
        email:
            since_version: 1.0
            expose: true
        enabled:
            since_version: 1.0
            expose: true
```

then i went on defining the functionality that fetches the data and should be using this exclusion policy defined above:

``` php
use FOS\RestBundle\Controller\FOSRestController;
use My\UserBundle\Model\UserQuery;
use FOS\RestBundle\Controller\Annotations as Rest;
use Tara\UserBundle\Response;


class UserController extends FOSRestController
{
    public function getUsersAction(){
        $view = $this->view();

        $query = new UserQuery();

        $users = $query->find();

        $users = new Response($users);
        $users = $users->getUsers();
        $view->setData(array( 'users' => $users), 200);
        $view->setSerializerVersion('1.1');


        $view->setTemplate('TaraUserBundle:User:user.html.twig');
        return $this->handleView($view);
    }
}
```

I've configured fos_rest and jms_serializer as followed:

``` yaml
fos_rest:
    view:
        formats:
            xml: true
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    service:
        serializer: jms_serializer.serializer
    serializer:
        version: ~
        groups: []

jms_serializer:
    metadata:
        cache: file
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        auto_detection: true
        directories:
            my_user_bundle:
                namespace_prefix: "My\UserBundle"
                path: "@MyUserBundle/Resources/config/serializer"
```

.when requesting with APPLICATION/XML accept header, which should use the serializer to create the output, I'm getting two unexpected results:
1. I get this error message as soon as i try to define a version for the serializer:

``` html
Fatal error: Call to undefined method JMS\Serializer\Serializer::setVersion() in \vendor\friendsofsymfony\rest-bundle\FOS\RestBundle\View\ViewHandler.php on line 203
```

i checked it out, and there is no setVersion defined in the serializer class. It means that either the the version of JMSSerializer installed automatically when installing FOSRestBundle using composer doesn't support the versioning or there is some other problem somewhere in the middle, of that I don't know.
1. one might think using this technic the ouptut created by the viewHandler would respect the exclusion policy defined; but either the Serializer has internal problems or the exclusion policies are not used when creating the response, and i can't get the fields in the result set to be excluded according to the defined exclusion policy. All the fields are available in the output...

Could anyone please help me figuring out if I've done (as usual) a mistake in configuration and usage of the bundles or these errors that i face are really there and how they can be fixed..
thanks.
