### ISSUE TITLE
Make pluralization configurable

### ISSUE THREAD

**Issue by Markkaz** [FriendsOfSymfony/FOSRestBundle#391]
I'm building a REST api for a Dutch application and use dutch words for the url's. In Dutch pluralization works differently than in English however.

For example I have the entity "Evenement". The plural form is "Evenementen"
When creating a controller like this:

``` php
class EvenementController extends FOSRestController
{
  public function getEvenementenAction() {}
  public function postEvenementenAction() {}
  public function getEvenementAction($id) {}
}
```

And use the following routing:

``` yaml
evenementen:
  type: rest
  prefix: /api
  resource: NTB\CoreBundle\Controller\EvenementController
```

I get the following routes:
- /api/evenementen (GET)
- /api/evenementen (POST)
- /api/evenements/3 (GET)

There are two possibilities to fix this I think:
1. Use the route name for all the urls
2. Let the programmer define the pluralized form in as an option

In both cases you don't need the pluralization code anymore. Which is never going to work for all languages.
