### ISSUE TITLE
How to configure in XML

### ISSUE THREAD

**Issue by purnama** [FriendsOfSymfony/FOSRestBundle#410]
Hi i'm using XML for my symfony2 config. how can i interpret this part in xml?

``` yaml
fos_rest:
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Acme\HelloBundle\Exception\MyExceptionWithASafeMessage': true
```

i cant use php namespace as tag name or attribute.

Thank you in Advanced
