### ISSUE TITLE
problem with binding POST to form with CURL

### ISSUE THREAD

**Issue by bartoszrychlicki** [FriendsOfSymfony/FOSRestBundle#490]
Hi All! 
I've read previous post about that problem and I have proper form type name (the same as singualar object) but still in my action the request post params are empty. Everything works fine when I use form in the browser. Also, I've got this working for diffrent objectm but not for this one. Maybe it's has something to do with beeing a child object? Anyone have a clue? Here are my settings:

``` yaml
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
```

that's the routing (POSTing does not work for "mood" object, but it works for "user" object"

``` yaml
users:
  type: rest
  resource: Wsh\Hay\RestBundle\Controller\UsersController

moods:
  type: rest
  resource: Wsh\Hay\RestBundle\Controller\MoodsController
  parent: users
```

And here is my controller action that should take care of posting:

``` php
public function postMoodAction(Request $request, $userId)
    {
        var_dump($request->request->all()); // is EMPTY
        $em = $this->getDoctrine()->getManager();
        $user = $em->find('WshHayRestBundle:User', $userId);

        if (!$user) {
            throw $this->createNotFoundException('Unable to find user with id '.$userId);
        }

        $mood = new Mood();
        $mood->setUser($user); //add user

        $form = $this->createForm(new MoodType(), $mood);


        $form->handleRequest($request);

        if($form->isValid()) {
            $em->persist($mood);
            $em->flush();

            return $this->redirectView(
                $this->generateUrl(
                    'get_user_mood',
                    array('id' => $userId)
                ).'.json',
                Codes::HTTP_CREATED
            );
        }
        return array(
            'form' => $form
        );
    } // post_user_mood POST /hay/users/{userId}/mood.{_format}
```

As You can see the request does not have passed any data

here is my FormType

``` php
class MoodType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('score')
        ;
        $builder->add('emotions', 'collection', array(
                'type'         => new EmotionType(),
                'allow_add'    => true,
                'by_reference' => false,
            )
        );

    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Wsh\Hay\RestBundle\Entity\Mood',
            'csrf_protection' => false,
        ));
    }

    public function getName()
    {
        return 'mood';
    }
}
```

And I try to test it with CURL like so:

``` bash
curl -v -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"mood": {"emotions":{ {"name":"anger", "value":"3", "sequence":"2"} } }, "score":12}' hayapi.local/app_dev.php/hay/users/11/mood.json
```

So, it's driving me crazy, any help would very appriciated!
