### ISSUE TITLE
BodyListener and default format

### ISSUE THREAD

**Issue by MiljenkoR** [FriendsOfSymfony/FOSRestBundle#495]
Hello,

BodyListener should apply default format if there is no Content-type set or if it is */*. 

Example configuration:

```
fos_rest:
    serializer:
        serialize_null: false
    routing_loader:
        default_format: json
        include_format: false
    param_fetcher_listener: force
    body_listener: true
    view:
        serialize_null: false
        formats:
            json: true

        templating_formats:
            html: true
        view_response_listener: force
    access_denied_listener:
        # all requests using the 'json' format will return a 403 on an access denied violation
        json: true
```

If no content-type set, this configuration will not convert body, but will be return json from controller,which is not supposed behavior.

On line 55 BodyListener.php $format is empty for this request.

POST /api/v1/user
accept:     "application/json"
content-type:   "_/_; charset=UTF-8"

This should fail back to default format, but do to empty $format, it's doesn't

This request behave well.

POST /api/v1/user
accept:     "application/json"
content-type:   "application/json; charset=UTF-8"

I am using Symfony 2.3.1 and current build of FOSRestBundle.
Regards,
Miljenko
