### ISSUE TITLE
Problem with Route tree when adding second child to route on the same level.

### ISSUE THREAD

**Issue by emgiezet** [FriendsOfSymfony/FOSRestBundle#507]
Hello!

I'm working on my Api. And the tree looks like this:

``` yaml
application:
    type:     rest
    resource: App\ApiBundle\Controller\ApplicationsController
    name_prefix:  api_

issue:
    type:     rest
    resource: App\ApiBundle\Controller\IssueController
    parent:   application
    name_prefix:  api_

article:
    type:     rest
    parent:   issue
    resource: App\ApiBundle\Controller\ArticleController
    name_prefix:  api_

page:
    type:     rest
    parent:   article
    resource: App\ApiBundle\Controller\PageController
    name_prefix:  api_

document:
    type:     rest
    resource: App\ApiBundle\Controller\DocumentController
    parent:   application
    name_prefix:  api_
```

It worked perfectly with issue, article & page. But when I want to connect another node to application `document` one it dont generate the routings.

```
No route found for "GET /api/applications/application-1/documents"
```

Only those are generated:

```
api_get_applications                    GET    ANY    ANY  /api/applications.{_format}
api_get_application                     GET    ANY    ANY  /api/applications/{slug}.{_format}
api_get_application_issues              GET    ANY    ANY  /api/applications/{slug}/issues.{_format}
api_get_application_issue               GET    ANY    ANY  /api/applications/{slug}/issues/{id}.{_format}
api_get_application_issue_articles      GET    ANY    ANY  /api/applications/{slug}/issues/{id}/articles.{_format}
api_get_application_issue_article       GET    ANY    ANY  /api/applications/{slug}/issues/{id}/articles/{title}.{_format}
api_get_application_issue_article_pages GET    ANY    ANY  /api/applications/{slug}/issues/{id}/articles/{title}/pages.{_format}
api_get_application_issue_article_page  GET    ANY    ANY  /api/applications/{slug}/issues/{id}/articles/{title}/pages/{no}.{_format}
```

All controllers are extending the `FOS\RestBundle\Controller\FOSRestController`
