### ISSUE TITLE
UnexpectedValueException in ViewHandler in PHP 5.5

### ISSUE THREAD

**Issue by rickard2** [FriendsOfSymfony/FOSRestBundle#536]
Hi

I've started getting this strange exception after upgrading to PHP 5.5.2. I've verified that everything works as usual when I switch back to PHP 5.4.

```
The Response content must be a string or object implementing __toString(), "boolean" given.
```

The controller is returning an array of entities, and then the ViewHandler seems to do something funky with it. 

I've got a JSON payload with full trace here: https://gist.github.com/rickard2/6660e8b410ebeb1579bb

Configuration: 

```
fos_rest:
  body_listener:
    decoders:
      json: fos_rest.decoder.json
  format_listener:
     default_priorities: [html, json, '*/*']
     fallback_format: html
  view:
    formats:
      json: true
    failed_validation: HTTP_BAD_REQUEST
  service:
    serializer: "montania_serializer"
```

Unfortunately I'm a bit behind on versions, so I'm running SF 2.1.3, rest 0.8.\* and rest-bundle 0.9.\* - I haven't verified this issue in newer versions.
