### ISSUE TITLE
name_prefix not work?

### ISSUE THREAD

**Issue by spolischook** [FriendsOfSymfony/FOSRestBundle#545]
I find that name_prefix parameter not valid in symfony's yaml parser. See this https://github.com/symfony/symfony/pull/334
And if I remove validation, name_prefix still not imported :(
I have this routing:

``` yml
google_calendar_api:
    type:     rest
    resource: Spolischook\GoogleCalendarBundle\Controller\ApiController
    prefix:   /api/calendar
    name_prefix: google_calendar_api_
    options:
        expose: true
```

I'm use Symfony 2.3 What I do wrong
