### ISSUE TITLE
Unable to find template "Foo:Users:getUsers.html.twig"

### ISSUE THREAD

**Issue by r8or0pz** [FriendsOfSymfony/FOSRestBundle#594]
**I get this error:**

```
Unable to find template "HoaxPartnerBundle:Users:getUsers.html.twig"
```

**config.yml:**

```
fos_rest:
    format_listener: 
        rules:
            - { path: '^/', priorities: ['html', 'json', 'xml'], fallback_format: json, prefer_extension: false }
    view:
        view_response_listener: true
```

**routing.yml:**

```
users:
    type:     rest
    resource: Hoax\PartnerBundle\Controller\UsersController
```

**UsersController:**

```
namespace Hoax\PartnerBundle\Controller;

use Hoax\PartnerBundle\Entity\VpnUsers;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use FOS\RestBundle\Controller\Annotations\View;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

class UsersController extends Controller
{
    /**
     * @return array
     * @View()
     */
    public function getUsersAction()
    {
        $users = $this->getDoctrine()->getEntityManager('vpnserver')->getRepository('HoaxPartnerBundle:VpnUsers')
            ->findAll();

        return array('users' => $users);
    }

    /**
     * @param User $user
     * @return array
     * @View()
     * @ParamConverter("user", class="HoaxPartnerBundle:VpnUsers", options={"entity_manager" = "vpnserver"})
     */
    public function getUserAction($user)
    {
        return array('user' => $user);
    }

}
```

If I change `view_response_listener` to `false`, I get this:

`The controller must return a response (Array(users => Array(0 => Object(Hoax\PartnerBundle\Entity\VpnUsers))) given).`

The solutions from this thread don't help: http://stackoverflow.com/questions/18010784/fos-rest-bundle-unable-to-find-template
