### ISSUE TITLE
Accept Header with version

### ISSUE THREAD

**Issue by amenophis** [FriendsOfSymfony/FOSRestBundle#610]
Hi,
I try to implement a REST API with this bundle, and i would like to specify the used version into the Accept header like this:

```
application/vnd.my.app;version=1.0
application/vnd.my.app+xml;version=1.0
application/vnd.my.app+json;version=1.0
```

I have this configuration:

```
fos_rest:
    view:
        view_response_listener: force
        formats:
            json: true
            xml: true
        mime_types:
            xml: ['application/vnd.my.app+xml']
            json: ['application/vnd.my.app+json']
    format_listener:
        rules:
            - { path: ^/api, priorities: [json, xml], fallback_format: json, prefer_extension: false }
            - { path: ^/, priorities: [html], fallback_format: html}
```

It works well for the following Accept Headers:

```
application/vnd.my.app // Get JSON output (Content-Type application/vnd.my.app+json)

application/vnd.my.app+json // Get JSON output (Content-Type application/vnd.my.app+json)

application/vnd.my.app+xml // Get XML output (Content-Type application/vnd.my.app+xml)
```

but doesn't work when I use:

```
application/vnd.my.app;version=1.0 // Get JSON output (Content-Type application/vnd.my.app+json)

application/vnd.my.app+json;version=1.0 // Get JSON output (Content-Type application/vnd.my.app+json)

application/vnd.my.app+xml;version=1.0 // Get JSON output (Content-Type application/vnd.my.app+json)
```

I would not define all the combinations of versions and types in the configuration but maybe it is the only choice ?

Could you help me about this ?
