### ISSUE TITLE
default_format is not applied to manually defined routes

### ISSUE THREAD

**Issue by xabbuh** [FriendsOfSymfony/FOSRestBundle#626]
Imagine the following configuration:

``` yaml
fos_rest:
    routing_loader:
        default_format: json
        include_format: false
```

and import some manual REST routes:

``` yaml
acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
    type:     rest
```

The imported routing configuration is:

``` yaml
acme_demo.get_users:
    path: /api/users
    defaults:
        _controller: AcmeDemoBundle:UsersController:getUsers
```

If you run `php app/console router:debug acme_demo.get_users`, you get something like the following output.

``` bash
[router] Route "acme_demo.get_users"
Name         acme_demo.get_users
Path         /api/users
Host         ANY
Scheme       ANY
Method       ANY
Class        Symfony\Component\Routing\Route
Defaults     
Requirements NO CUSTOM
Options      compiler_class: Symfony\Component\Routing\RouteCompiler
Path-Regex   #^/api/users$#s
```

Is it intended that the default_format value (json with this configuration) is not applied to this manual route definition?

Actually, to achieve this behaviour I had to modify my routing definition like this:

``` yaml
acme_demo.get_users:
    path: /api/users
    defaults:
        _controller: AcmeDemoBundle:UsersController:getUsers
        _format:     json
```
