### ISSUE TITLE
No matching accepted Response format could be determined

### ISSUE THREAD

**Issue by Gnucki** [FriendsOfSymfony/FOSRestBundle#631]
Since the last updates, I got a "No matching accepted Response format could be determined" when I call a route with an url starting with `/api`.

Here is the configuration:

``` yml
# FOSRest Configuration
fos_rest:
    param_fetcher_listener: force
    routing_loader:
        default_format: json
    access_denied_listener:
        json: true
    format_listener:
        rules:
            - { path: ^/api, priorities: ['json', 'html', '*/*'], fallback_format: json, prefer_extension: true }
            - { path: ^/, priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
```

I didn't change anything.
