### ISSUE TITLE
Unable to configure Resource collection, throws up on `parent` param.

### ISSUE THREAD

**Issue by HelloGrayson** [FriendsOfSymfony/FOSRestBundle#66]
Getting an exception when trying to configure a Resource collection according to the README.

_Configuration:_

``` yaml
users:
  type:     rest
  resource: "@AcmeHello\Controller\UsersController"

comments:
  type:     rest
  parent:   users
  resource: "@AcmeHello\Controller\CommentsController"
```

_Exception:_

```
InvalidArgumentException: Yaml routing loader does not support given key: "parent". 
Expected one of the (type, resource, prefix, pattern, options, defaults, requirements).   
```
