### ISSUE TITLE
It should not define 'serialize_null' option twice.

### ISSUE THREAD

**Issue by docteurklein** [FriendsOfSymfony/FOSRestBundle#663]
Currently, the docs and the configuration tree allows:

``` yaml
fos_rest:
    view:
        serialize_null: true
    serializer:
        serialize_null: true

```

Only the one under `serializer` is taken into account.
