### ISSUE TITLE
[Routing] Pluralization doesn't seem to work

### ISSUE THREAD

**Issue by sescandell** [FriendsOfSymfony/FOSRestBundle#675]
Hi,

Following the documentation, I made the following simple code:

``` php
<?php

namespace Acme\DemoBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Acme\DemoBundle\Entity\Media;
use FOS\RestBundle\Controller\Annotations;
use Acme\DemoBundle\Form\MediaType;
use JMS\SecurityExtraBundle\Annotation\Secure;

class MediaController extends Controller
{
    public function getMediasAction()
    {

    }

    public function getMediaAction(Media $media)
    {

    }

    /**
     * @Secure(roles="ROLE_USER")
     * @param Media $media
     * @return multitype:Media
     */
    public function likeMediaAction(Media $media)
    {

    }

    /**
     * @Secure(roles="ROLE_USER")
     * @Annotations\View(
     *  template = "AcmeDemoBundle:Media:newMedia.html.twig",
     *  templateVar = "form"
     * )
     */
    public function postMediaAction(Request $request)
    {
       ...    
    }

    /**
     * @Annotations\View()
     */
    public function newMediaAction()
    {
    }
}

```

and here is the routing declaration:

``` yaml
## File app/config/routing.yml
_acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"

_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#############
## File AcmeDemoBundle/Resources/config/routing.yml
_acme_demo_rest:
    type: rest
    prefix: /api
    resource: "@AcmeDemoBundle/Resources/config/routing_rest.yml"

## File AcmeDemoBundle/Resources/config/routing_rest.yml
_media_api_rest:
    type: rest
    resource: Acme\DemoBundle\Controller\MediaController
    prefix: /v1
    name_prefix: _api_1_
```

I so was expecting that all "generated routes" start with `/api/v1/medias`. But here is the `router:debug` result:

``` console
_api_1_like_media                 PATCH    ANY    ANY  /api/v1/media/{media}/like.{_format} 
 _api_1_new_media                  GET      ANY    ANY  /api/v1/media/new.{_format}          
 _api_1_get_medias                 GET      ANY    ANY  /api/v1/medias.{_format}             
 _api_1_get_media                  GET      ANY    ANY  /api/v1/media/{media}.{_format}      
 _api_1_post_media                 POST     ANY    ANY  /api/v1/media.{_format}
```

Whereas, given the document, I was expecting something like:

``` console
_api_1_like_media                 PATCH    ANY    ANY  /api/v1/media/{media}/like.{_format} 
 _api_1_new_media                  GET      ANY    ANY  /api/v1/medias/new.{_format}          
 _api_1_get_medias                 GET      ANY    ANY  /api/v1/medias.{_format}             
 _api_1_get_media                  GET      ANY    ANY  /api/v1/medias/{media}.{_format}      
 _api_1_post_media                 POST     ANY    ANY  /api/v1/medias.{_format}
```

Am I doing something wrong?

Thank you,
