### ISSUE TITLE
Unable to set default format via annotations

### ISSUE THREAD

**Issue by chetzof** [FriendsOfSymfony/FOSRestBundle#680]
```
fos_rest:
    param_fetcher_listener: force
    view:
        view_response_listener: true
    body_listener: true
    routing_loader:
        include_format: false
```

```
use FOS\RestBundle\Controller\Annotations\Route;
/**
 * @Prefix("/admin")
 * @NamePrefix("gcb_user_")
 * @Route(defaults={"_format"="html"})
 */
class UserController extends FOSRestController implements ClassResourceInterface
{
    /**
     * @Route(defaults={"_format"="html"})
     */
    public function cgetAction()
    {
        ....
    }
}
```

then 

```
app/console router:debug gcb_user_get_users 
[router] Route "gcb_user_get_users"
Name         gcb_user_get_users
Path         /admin/users
Host         ANY
Scheme       ANY
Method       GET
Class        Symfony\Component\Routing\Route
Defaults     _controller: MyBundle:User:cget
             _format: NULL
Requirements 
Options      compiler_class: Symfony\Component\Routing\RouteCompiler
             i18n: false
Path-Regex   #^/admin/users$#s
```

as you see for some reason the `_format` is `null`
the `@Route(defaults={"_format"="html"})` annotation does not work nor when being set to method neither to the whole class

**however setting it via yaml suddenly works**

```
my_bundle.user:
    resource: "@MyBundle/Controller/UserController.php"
    type: rest
    defaults:
        _format: html
    options:
        i18n: false
```
