### ISSUE TITLE
Name prefix issue in Yaml

### ISSUE THREAD

**Issue by aosmialowski** [FriendsOfSymfony/FOSRestBundle#693]
So, there's a route:

``` yaml
acme_demo:
  resource: Acme\DemoBundle\Controller\DemoController
  type: rest
  name_prefix: api_v1_
```

which cause the following exception thrown:

``` php
FileLoaderLoadException: Cannot import resource "/var/www/sf/src/Acme/DemoBundle/Resources/config/routing/v1.yml" from "/var/www/sf/src/Acme/DemoBundle/Resources/config/routing.yml". (The routing file "/var/www/sf/src/Acme/DemoBundle/Resources/config/routing/v1.yml" contains unsupported keys for "acme_demo": "name_prefix". Expected one of: "resource", "type", "prefix", "pattern", "path", "host", "schemes", "methods", "defaults", "requirements", "options", "condition".)
```

while it works perfectly if used as annotation:

``` php
use FOS\RestBundle\Controller\Annotations as REST;

/**
 * @REST\NamePrefix("api_v1_")
 */
class AcmeController extends Controller {}
```

A bug? A misconfiguration?
