### ISSUE TITLE
format_listener is being ignored

### ISSUE THREAD

**Issue by dadamssg** [FriendsOfSymfony/FOSRestBundle#695]
With the following format i expect when i issue a GET request in my browser to an endpoint i would get json back:

``` yaml
fos_rest:
    format_listener:
        rules:
            - { path: ^/api, priorities: [json, xml], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
    view:
        formats:
            xml: true
            json: true
            html: true
        mime_types:
            json: ['application/json', 'application/x-json']
            xml: ['application/xml']
    routing_loader:
        default_format: json
        include_format: false

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
```

When i visit the following in my browser:

`http://myapp.dev/app_dev.php/api/users/3`

I get an XML response back. I don't know what i have configured incorrectly. I expect the default to be json.
