### ISSUE TITLE
Routing bug, when you use same controller names, but different namespaces.

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSRestBundle#697]
Hey guys,

I've the following in my routing.yml.

``` yml
RestBundleFoo:
    resource: "@RestBundle/Resources/config/routing/Foo.yml"
    type:     rest
    prefix:   /foo

RestBundleBar:
    resource: "@RestBundle/Resources/config/routing/Bar.yml"
    type:     rest
    prefix:   /bar
```

Foo.yml

``` yml
RestBundleFooProducts:
    type:     rest
    resource: Foo.Products.Controller
```

Bar.yml

``` yml
RestBundleBarProducts:
    type:     rest
    resource: Bar.Products.Controller
```

Foo is a module, where I can administrate products with my admin bundle.
Bar is a module, where users can search for products. I use FOS_Elastica for this.

So, I need to create paginated lists in both of these modules with the following URLs:

Foo: /foo/products --> paginated product list for my admin area.
Bar: /bar/products --> paginated search results of my products for my users.

If I use both of these routing configuration files, only the second route works. If I request the first route, the FOSRestBundle throws an Exception and Symfony2 responses with a 405 (METHOD NOT ALLOWED).

Controller:

``` php
namespace RestBundle\Controller\Foo;

class ProductsController extends ApiController
{
    // This creates a paginated list of products for the admin section
    // This action should be accessible over /foo/products
    // But this doesn't work (405 Method not allowed)
    // If I change the method name to getProductssAction (Notice the second 's')
    // and request /foo/productss, everything works like a charm 
    public function getProductsAction($page = 1, $limit = 20, Request $request)
    {
    }
}
```

``` php
namespace RestBundle\Controller\Bar;

class ProductsController extends ApiController
{
    // This uses FOS_Elastica for searching products in my
    // index and create a paginated result list.
    // This works like a charm
    public function getProductsAction($name, $page = 1, $limit = 20)
    {
    }
}
```

Security.yml

``` yml
access_control:
    - { path: ^/foo, roles: [ROLE_FOO_USER]} 
    - { path: ^/bar, roles: [ROLE_BAR_USER]}
```

Please tell me, if you need more information.

Greetings,

Christian
