### ISSUE TITLE
Class could not be determined for Controller identified by

### ISSUE THREAD

**Issue by Shine-neko** [FriendsOfSymfony/FOSRestBundle#701]
Hey, 

I quite bizzare worries. It seems that the loader does not like class that begins with the letter L.

``` yaml
_convention_api:
    type: rest
    prefix: /v1/lexique
    resource: "Rina\Bundle\CardBundle\Controller\LexiqueController"
    name_prefix:  api_lexique_
```

``` code
( ! ) Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Class could not be determined for Controller identified by "Rina\Bundle\CardBundle\Controllerâ€¨exiqueController".' in /vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php on line 100
```

If I replace LexiqueController by DexiqueController it works
