### ISSUE TITLE
"routing_loader: default_format: json"     doesn't work 

### ISSUE THREAD

**Issue by hgraca** [FriendsOfSymfony/FOSRestBundle#712]
Hi,

I'm trying to set up a controller response to be always json but unfortunatly I can't figure out how to set up the default_format in the config file. 
It comes back as xml.

The rest bundle config is this:

``` yml
fos_rest:
    disable_csrf_role:    ~
#    access_denied_listener:
#        # Prototype
#        name:                 []
    param_fetcher_listener:  false
    cache_dir:            %kernel.cache_dir%/fos_rest
    allowed_methods_listener:  false
    routing_loader:
        default_format:       json
        include_format:       false
    body_converter:
        enabled:              false
        validate:             false
        validation_errors_argument:  validationErrors
    service:
        router:               router
        templating:           templating
        serializer:           jms_serializer.serializer
        view_handler:         fos_rest.view_handler.default
        inflector:            fos_rest.inflector.doctrine
        validator:            validator
    serializer:
        version:              ~
        groups:               []
        serialize_null:       true
    view:
        default_engine:       twig
#        force_redirects:
#            # Prototype
#            name:                 []
#        mime_types:
#            json: ['text/html','application/json','application/x-json','application/javascript'] #fallback browser (text/html) to json
        formats:
            json:  true
            jsonp: true
            xml:   true
#        templating_formats:
#            # Prototype
#            name:                 []
        view_response_listener:  true
        failed_validation:    400
        empty_content:        204
        exception_wrapper_handler:  FOS\RestBundle\View\ExceptionWrapperHandler
        serialize_null:       false
        jsonp_handler:
            callback_param:       callback
            mime_type:            application/javascript+jsonp
    exception:
#        codes:
#            # Prototype
#            name:                 []
#        messages:
#            # Prototype
#            name:                 []
    body_listener:
        throw_exception_on_unsupported_content_type: false
#        decoders:
#            # Prototype
#            name:                 []
    format_listener:
        rules:
            # Prototype array
            -
                # URL path info
                path:                 '^/'
                # URL host name
                host:                 ~
                prefer_extension:     true
                fallback_format:      json
                priorities: ['json','jsonp','xml']
        media_type:
            version_regex:        '/(v|version)=(?P<version>[0-9\.]+)/'
```

This is my action:

``` php
    /**
     * @Rest\Get("/event_collection")
     * @Rest\View()
     */
    public function indexAction()
    {
        // ...
        return array('eventCollection' => $eventCollection);
    }
```

And this is what comes out of the debug command:

```
vagrant@dev3 $ app/console router:debug index
[router] Route "index"
Name         index
Path         /api/v1.0/event_collection
Host         ANY
Scheme       ANY
Method       GET
Class        Symfony\Component\Routing\Route
Defaults     _controller: HgracaApiBundle:Default:index
             _format: json
Requirements 
Options      compiler_class: Symfony\Component\Routing\RouteCompiler
Path-Regex   #^/api/v1\.0/event_collection$#s
```

which states the _format is json, but it still spits out xml...

Also, even if I add that config to my routing, it still doesn't work:

``` yml
aggregator_api:
#    resource: "@HgracaApiBundle/Controller/DefaultController.php" # this doesn't work
    resource: "Hgraca\Bundle\ApiBundle\Controller\DefaultController"
    type:     rest
    defaults:
        _format: json
    prefix:   /api/v1.0
```

Finnally, if I change the configuration to require the JSON extension in the URL, it works (although this is not what I want):

``` yml
fos_rest:
    routing_loader:
        default_format:       json
        include_format:       true
```

Any idea about what I'm doing wrong?

Tkx
