### ISSUE TITLE
duplicated routes 

### ISSUE THREAD

**Issue by joanteixi** [FriendsOfSymfony/FOSRestBundle#716]
I'm not sure if i'm doing something wrong, but when I define a resource as rest type, and also in some of the controllers, override the default routing configuration and add routing annotations, the router:debug show duplicate routes with prefix and without prefix. 

some example:

``` YAML
search:
    type:     rest
    prefix:   /api/v2
    resource: Onfan\ApiBundle\Controller\SearchController
    options:
        i18n: false
```

In searchController, I add some annotations:

``` PHP
 /**
   * @Get("searchExternal", name="_myname")
   *
   */
   public function getSearchExternalAction(Request $request)
```

In console, router:debug |grep searchExternal shows:

``` BASH
_myname                  GET      ANY    ANY  /searchExternal
get_search_external_v4   GET      ANY    ANY  /api/v2/searchExternal.{_format}
```

(I  add options, i18n false, but adding also the route name begging with _ so the i18nRoutingBundle   skip to process it).

It's some kind of bug or i'm doing something wrong? 

Thanks, 

Joan Teixidó

**Comment by feridmovsumov** [comment]
I have the same problem. 

I added custom route for count action

```yml
brands_count:
    pattern:  /brands/count.{_format}
    defaults: { _controller: ApiBundle:Brand:getCount, _format: json }
    methods:  [GET]
```
and when I run php console debug:route
```json
brands_count             GET    ANY    ANY  /api/v2/brands/count.{_format}
get_count                  GET    ANY    ANY  /api/v2/count.{_format}
```
