### ISSUE TITLE
CSS & Images always sends JSON headers

### ISSUE THREAD

**Issue by johndoesenior** [FriendsOfSymfony/FOSRestBundle#733]
After I upgraded FOSRestBundle from 1.0.0 to 1.3 version, my css & images stop interpreted as `css` files but as `json`.

I.e. `style.css` suppose to send `text/css` header, but sends instead `text/json`

Configuration:

``` yaml
fos_rest:
    routing_loader:
        include_format: false
    view:
        view_response_listener: force
        failed_validation: HTTP_BAD_REQUEST
        formats:
            rss: false
            xml: true
            json: true
            html: true
        templating_formats:
            html: true
    access_denied_listener:
        json: true
    format_listener:
        rules:
            -
                # URL path info
                path:                 '^/'
                host:                 ~
                prefer_extension:     true
                fallback_format:      json
                priorities: [ 'json', 'xml', 'html', '*/*' ]
    body_listener:
        decoders:
            json: fos_rest.decoder.json
            xml: fos_rest.decoder.xml
    param_fetcher_listener: true
    allowed_methods_listener: true
```
