### ISSUE TITLE
Select methods for automatic routing

### ISSUE THREAD

**Issue by bzzzm** [FriendsOfSymfony/FOSRestBundle#747]
Hello,

I'm building an REST API with 2 main parts, one public (no auth) and one private (with wsse auth).

In the private part I do all the heavy stuff (adding resources, linking them etc etc).
In the public part, I mostly display the resources, but I also have a few posts (eg contact form).

Here is my `app/config/routing.yml``

```
acme_public:
    type: rest
    resource: "@AcmePublicBundle/Resources/config/routing.yml"
    prefix:   /public/

acme_private:
    type: rest
    resource: "@AcmePrivateBundle/Resources/config/routing.yml"
    prefix:   /private/
```

and `AcmePublicBundle/Resources/config/routing.yml`

```
acme_public_resource1:
    type: rest
    prefix: /res1
    resource: "Acme\OtherBundle\Controller\Res1Controller"
    name_prefix: acme_public_res1_

acme_public_resource2:
    type: rest
    prefix: /res2
    resource: "Acme\OtherBundle\Controller\Res2Controller"
    name_prefix: acme_public_res2_
```

Is there a way to specify in the public routing.yml to accept only GETs for `acme_public_resource1`, but accept post/delete for `acme_public_resource2` (so i can post on /private/res1, but not on /public/res1.. and still post on both /public/res2 and /private/res2? I tried with _method, but no success. Is there any clean approach to this or checking the route in the controller (or some listener) is the best solution?

Thank you
