### ISSUE TITLE
Exception map being ignored

### ISSUE THREAD

**Issue by dadamssg** [FriendsOfSymfony/FOSRestBundle#748]
My exception map seems to be getting ignored. I'm throwing an `\Exception('testing...')`  in my controller just to see if it works and i'm still seeing the "testing..." message being return in my JSON response even though i don't have that base exception class in my exception map. 

Do i have something misconfigured? I'm using the `dev` environment through `app_dev.php`.

``` yaml

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: ^/api, priorities: [html, json, xml], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: [ 'html','json'], fallback_format: ~, prefer_extension: false }
    view:
#        exception_wrapper_handler: MyProject\MyBundle\Handler\FormExceptionFormatter
        view_response_listener: 'force'
        formats:
            xml: true
            json: true
            html: true
        templating_formats:
            html: true
    service:
        serializer: jms_serializer.serializer
    exception:
        codes:
            'Symfony\Component\Security\Core\Exception\AccessDeniedException': 401
        messages:
            'Symfony\Component\Security\Core\Exception\AccessDeniedException': true
```

Controller

``` php
class TestController extends BaseController
{
    public function testAction(Request $request)
    {
        throw new \Exception('testing...');
    }
}
```

JSON response

``` json
{"code":500,"message":"testing..."}
```
