### ISSUE TITLE
Unrecognized Options For Array Normalizer

### ISSUE THREAD

**Issue by 0x7061** [FriendsOfSymfony/FOSRestBundle#759]
I checked out 1.3.1 and if I try to enable the camel case array normalizer like in the documentation I get: `Unrecognized options "array_normalizer" under "fos_rest.body_listener"`.
Did I miss something?

Everything else is working perfectly fine.

```
body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys # <-- error
        decoders:
            json: fos_rest.decoder.json
            xml: fos_rest.decoder.xml
```
