### ISSUE TITLE
RestBundle throw exception: The server returned a "415 Unsupported Media Type".

### ISSUE THREAD

**Issue by saharabear** [FriendsOfSymfony/FOSRestBundle#790]
Hi, 

I use FOSRestBundle to generate REST API, my application works well on local, but when I deploy it to apache on a Ubuntu Server, always get : The server returned a "415 Unsupported Media Type".

I have accept and content-type to application/json. my config.yml is: 

```
sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        force_redirects:
            html: false
        formats:
            json: true
            xml: false
        templating_formats:
            html: false
    format_listener:
        rules:
            - { path: ^/, priorities: [ json ], fallback_format: json }
    routing_loader:
        default_format: json
```

Thanks
