### ISSUE TITLE
Import routes from a controller directory

### ISSUE THREAD

**Issue by jorgebg** [FriendsOfSymfony/FOSRestBundle#796]
With `SensioFrameworkExtraBundle` you can [import routes from a controller directory](http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/routing.html#activation):

```yaml
# app/config/routing.yml
blog:
    resource: "@SensioBlogBundle/Controller"
    type:     annotation
```

Can [`FosRestBundle`](https://github.com/FriendsOfSymfony/FOSRestBundle) do the same?

```yaml
# app/config/routing.yml
blog:
    resource: "@SensioBlogBundle/Controller"
    type:     rest
```
