### ISSUE TITLE
Issue during request binding to form

### ISSUE THREAD

**Issue by skay973** [FriendsOfSymfony/FOSRestBundle#810]
Hi everyone, 

i'm facing a problem and after several hours of search im still stuck with my problem.

I set up the FOSRestBundle, the GET works perfectly but the POST... not at all..

I have a Todo entity with a content and a user relation (quite simple). I have my FormType and in my controller, i use createNamed to generate the form, avoiding namespaces issues.

here is my FormType :

```php
class RestTodoType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('content')
            ->add('user')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Efl\TodoBundle\Entity\Todo',
            'csrf_protection' => false
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'rest_todo';
    }
}
```

Here is my controller :

```php
public function postTodosAction(Request $request)
    {
        echo $request;
        $entity = new Todo();
        $form = $this->get('form.factory')->createNamed('', new RestTodoType(), $entity);
        //$form = $this->createForm(new RestTodoType(), $entity);
        $form->bind($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirectView(
                $this->generateUrl(
                    'get_todo',
                    array('user' => $entity->getUser(), 'id' => $entity->getId())
                ),
                Codes::HTTP_CREATED
            );
        }

        return array(
            'form' => $form,
        );
    }
```

and here is my config.yml :

```yaml
# FOS RestBundle
fos_rest:
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json
    disable_csrf_role: ROLE_API
```
and here is my curl call :
![capture_d cran_071214_070105_pm](https://cloud.githubusercontent.com/assets/2963098/3562231/26579b52-09e6-11e4-9087-0a2946236b43.jpg)

what am i doing wrong ?
