### ISSUE TITLE
access_denied_listener prevents custom message in AuthenticationException

### ISSUE THREAD

**Issue by websirnik** [FriendsOfSymfony/FOSRestBundle#815]
When I'm throwing AuthenticationException in the controller:

``` php
throw new AuthenticationException('My message');
```

I'm expecting the following response:

``` json
{"code":401,"message":"My message"}
```

Instead I'm getting

``` json
{"code":401,"message":"You are not authenticated"}
```

After debugging, it turned out that  throwing AuthenticationException also triggers HttpException with the message "You are not authenticated". This message gets into the response. I'm not sure whether it's expected behaviour, but I'm failing to get "My message" in the response. How do I do it?

Here is parts of my current config.

``` yaml
twig:
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

fos_rest:
    access_denied_listener:
        json: true              
    exception:
        codes:
            'Symfony\Component\Security\Core\Exception\AuthenticationException': 401
        messages:
            'Symfony\Component\Security\Core\Exception\AuthenticationException': true
```

*making `access_denied_listener:  json: false` fails to produce any response at all
