### ISSUE TITLE
Resources controller actions conflicts

### ISSUE THREAD

**Issue by ogizanagi** [FriendsOfSymfony/FOSRestBundle#820]
Hi!

I've got an issue when trying to define some route for resources under another one.
### First resource:

_@Rest\RouteResource("device")_

``` yaml
devices:
    type:     rest
    resource: ACME\APIBundle\Controller\DeviceController
    name_prefix: api_devices_
```

``` php

@Rest\RouteResource("device")
class DeviceController extends FOSRestController
{
    public function cgetAction() { ... }
    public function getAction($id) { ... }
}
```
### Second resource:

_@Rest\RouteResource("devices/access")_

``` yaml
app_accesses:
    type:     rest
    resource: ACME\APIBundle\Controller\AppAccessController
    name_prefix: api_app_accesses_

```

``` php

@Rest\RouteResource("devices/access")
class AppAccessController extends FOSRestController
{
    public function cgetAction() { ... }
    public function getAction($id) { ... }
}
```

When trying to contact http://acme.com/api/devices/accesses, I expect to call `AppAccessController:cgetAction`.
Instead, I inexplicably falls on `DeviceController:getAction`

I also tried to define manually the route on the `AppAccessController:cgetAction`, but it is the same resut.
The only way to achieve what I want, is by changing the **@Rest\RouteResource("devices/access")** resource name by another one (_access_ for instance), or by changing the `AppAccessController:cgetAction` method for `cgetAllAction` for instance.

**Question is:** Is there a proper way to achieve my goal ? Is this strange behaviour normal ?
