### ISSUE TITLE
How to keep part of app untouchable

### ISSUE THREAD

**Issue by EnchanterIO** [FriendsOfSymfony/FOSRestBundle#839]
Hi,

I decided to create REST API for mobile. My rest conf. looks like:

```
fos_rest:
param_fetcher_listener: true
body_listener: true
view:
    view_response_listener: true
    formats:
        xml:  true
        json: true
    templating_formats:
        html: true
format_listener:
    rules:
        - { path: ^/api, priorities: [ json, html, xml ], fallback_format: ~, prefer_extension: false }
```

okay that works good for /api I would say... but I am having problem with my web application now. 
When I apply this:

```
    - { path: '^/',  priorities: [ '*/*'], fallback_format: html, prefer_extension: true }
```

The page seems to be working BUT! some of my function are corrupted.
For example:

```
var url=Routing.generate('group_create_generate_followers_ids');

$.post(url, null, function(data) {


group_create_generate_followers_ids:
path:  /groups/creategroup/generatefollowersids/
defaults: { _controller: "GroupsBundle:Groups:GenerateFollowersIds",_format: json }
options:
    expose: true  
```

And in the controller I have:

```
if ($request->getRequestFormat() == 'json') {
```

So you can imagine... it's not working. Can I somehow configure this bundle to DON'T TOUCH ANYTHING THAT DOES NOT STARTS WITH " - { path: ^/api, " ?  

When I remove this line: "- { path: '^/',  priorities: [ '_/_'], fallback_format: html, prefer_extension: true }" 

I get: "No matching accepted Response format could be determined"

So... how to configure it properly plese?
