### ISSUE TITLE
Unwanted escaping

### ISSUE THREAD

**Issue by JeroenDeDauw** [FriendsOfSymfony/FOSRestBundle#840]
I have an array with some URLs in my controller method.

```
return $this->handleView( $this->view( $arrayWithUrls ) );
```

While these URLs looks like `http://foo.bar/baz`, they end up like `http:\/\/foo.bar\/baz` in the reply of my API. I have no idea what is adding these back slashes. And I'm not even sure why you'd escape a forward slash. How can I get rid of this?

Some maybe relevant config:

```
jms_serializer:
    visitors:
        json:
            options: JSON_PRETTY_PRINT

fos_rest:
    view:
        view_response_listener: force
        formats:
            json: true
        templating_formats:
            html: false
    routing_loader:
        include_format: false
        default_format: json
```

I checked what `JsonSerializationVisitor` is doing, and it seems to get the URLs in good form, and not mess them up.
