### ISSUE TITLE
ExceptionController overwrite the normal one for all routes

### ISSUE THREAD

**Issue by jbouzekri** [FriendsOfSymfony/FOSRestBundle#850]
Hi,

When using the exception controller, It changes the behavior for all routes event the ones whose are not of type rest.

In my application, all my rest routes are prefixed by /api : 

``` yaml
#app/config/routing.yml
my_bundle_api:
    resource: "@MyBundle/Resources/config/routing/api.yml"
    prefix:   /api

#@MyBundle/Resources/config/routing/api.yml
categories:
    type: rest
    resource: project.category.controller

questions:
    type: rest
    resource: project.question.controller
```

All my api routes support only the json format. I have the following rest bundle configuration : 

``` yaml
twig:
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

fos_rest:
    body_listener: true
    view:
        formats:
            json: true
            html: false
        templating_formats:
            html: false
        view_response_listener: 'force'
    routing_loader:
        default_format: json
        include_format: true
    exception:
        codes:
            'Symfony\Component\Security\Core\Exception\InsufficientAuthenticationException': 401
        messages:
            'Symfony\Component\Security\Core\Exception\InsufficientAuthenticationException': true
```

If I go to an unknown url like /toto, I have a 500 error code and when I dump the Exception, it said : 

``` php
object(Symfony\Component\HttpKernel\Exception\UnsupportedMediaTypeHttpException)[1592]
  private 'statusCode' (Symfony\Component\HttpKernel\Exception\HttpException) => int 415
  private 'headers' (Symfony\Component\HttpKernel\Exception\HttpException) => 
    array (size=0)
      empty
  protected 'message' => string 'Format 'html' not supported, handler must be implemented' (length=56)
  private 'string' (Exception) => string '' (length=0)
  protected 'code' => int 0
  protected 'file' => string '/home/jobou/workspace/certiz/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/View/ViewHandler.php' (length=100)
  protected 'line' => int 304
```

I tried to enable the html in the templating_formats. When I do this and I go to an unknown route, there is the standard SF2 error with a 404 code. However now, all my api routes authorize html in the _format parameter. It seems I go in circle. Maybe I am doing it wrong but I think the ExceptionController should fallback to the default one if a route is not prefixed by something meaning we are in the rest context.

Thanks in advance
