### ISSUE TITLE
Get the http response code status sent by Symfony

### ISSUE THREAD

**Issue by saro0h** [FriendsOfSymfony/FOSRestBundle#856]
Hi,

Here is my config of the FOSRestBundle:

```yml
fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    format_listener:
        rules:
           - { path: ^/api/, priorities: [json], fallback_format: false, prefer_extension: true }
    view:
        view_response_listener: 'force'
    param_fetcher_listener: force
    serializer:
      serialize_null: true
```

My problem is basically that everytime I get an error, I get a 406 http response code status.

![capture d ecran 2014-08-28 a 22 50 15](https://cloud.githubusercontent.com/assets/667519/4082845/9f612ab6-2ef5-11e4-8278-85a67fe0d27f.png)

Basically, I would like to get the real  http response code status sent by Symfony.

Did I do something wrong?
