### ISSUE TITLE
CSS and images are served as HTML

### ISSUE THREAD

**Issue by SpartakusMd** [FriendsOfSymfony/FOSRestBundle#857]
Hello. I began to use FOSRestBundle in my Symfony 2.3 project. All was fine, but suddenly content-type became wrong, I played a little and now in app/config/config.xml I have this code:

```
sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters: true }

fos_rest:
    param_fetcher_listener: true
    format_listener: true
#        rules:
#              - { path: ^/api/, priorities: ['json', 'html', 'xml'], fallback_format: ~, prefer_extension: true }
#              - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
    view:
        view_response_listener: true
```

This gives correct content-types for everything, except if I call API's without format I get exception. To get rid of the exception I uncomment the format_listener rules and remove true from him, but everything except api is now served as HTML. What could be wrong?
