### ISSUE TITLE
While returning $validationErrors the status code is 200

### ISSUE THREAD

**Issue by cve** [FriendsOfSymfony/FOSRestBundle#867]
Hi,

In the doc https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Resources/doc/3-listener-support.md#validation there is simple example with ConstraintViolationList, but when I replace the line 

```
// Handle validation errors 
```

with

```
return $validationErrors;
```

The response contains serialized errors (which is fine), but the status code is 200, which should be 422. Is there any way to do it automatically?

my rest conf:

```
fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    routing_loader:
        default_format: json
        include_format: false
    view:
        view_response_listener: true
        formats:
            json: true
```

my controller:

```
/**
 * @ParamConverter("category", converter="fos_rest.request_body")
 * @Post("/categories")
 * @View()
 */
public function postCategoryAction(Category $category, ConstraintViolationListInterface $validationErrors)
{
    if (count($validationErrors) > 0) {
        return $validationErrors;
    }

    $this->get('category_manager')->save($category);

    return $category;
}
```
