### ISSUE TITLE
Is there a way to customize router format

### ISSUE THREAD

**Issue by jerryladoo** [FriendsOfSymfony/FOSRestBundle#869]
Hi there, 

I am new to FOSRestBundle, now I am trying to customize my router format in order to handle _csv_ format or other possible format like _pdf_. I can get _json_ through this router "/report.json", what the best practice/approach should I follow/use if I want have a router like "/report.csv", which lets user to download/view report in _csv_ format, or "/report.pdf", or "/data.report"? Is it possible to do that way?

Currently I have followed this [doc](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Resources/doc/2-the-view-layer.md) for customizing view handler, but I have got an exception `No route found for "GET /reports/26.csv`, after that I gave `csv:true` in `formats` settting but I had got the following:

```
The format "csv" is not supported for serialization.

500 Internal Server Error - UnsupportedFormatException

Stack Trace

in /acme/vendor/jms/serializer/src/JMS/Serializer/Serializer.php at line 76   -
    public function serialize($data, $format, SerializationContext $context = null)
    {
        if ( ! $this->serializationVisitors->containsKey($format)) {
            throw new UnsupportedFormatException(sprintf('The format "%s" is not supported for serialization.', $format));
        }
        if (null === $context) {
at Serializer ->serialize (object(Report), 'csv', object(SerializationContext)) 
in /acme/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/View/ViewHandler.php at line 434   +
at ViewHandler ->initResponse (object(View), 'csv') 
in /acme/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/View/ViewHandler.php at line 407   +
at ViewHandler ->createResponse (object(View), object(Request), 'csv') 
in /acme/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/View/ViewHandler.php at line 301   +
at ViewHandler ->handle (object(View)) 
in /acme/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/Controller/FOSRestController.php at line 90   +
at FOSRestController ->handleView (object(View)) 
in /acme/MyBundle/Controller/MyController.php at line 86   +
at MyController ->getReportAction ('26')
at call_user_func_array (array(object(MyController), 'getReportAction'), array('26')) 
in kernel.root_dir/bootstrap.php.cache at line 2931   +
at HttpKernel ->handleRaw (object(Request), '1') 
in kernel.root_dir/bootstrap.php.cache at line 2903   +
at HttpKernel ->handle (object(Request), '1', true) 
in kernel.root_dir/bootstrap.php.cache at line 3042   +
at ContainerAwareHttpKernel ->handle (object(Request), '1', true) 
in kernel.root_dir/bootstrap.php.cache at line 2310   +
at Kernel ->handle (object(Request)) 
in /acme/web/app_dev.php at line 37   +
```

and I received a completely empty view if I had left the setting in `templating_formats`.

viewHandler.yml

```
services:
    acme.view_handler.csv:
        class: acme\MyBundle\View\CsvViewHandler

    acme.view_handler:
        parent: fos_rest.view_handler.default
        calls:
            - ['registerHandler', [ 'csv', [@acme.view_handler.csv, 'createResponse'] ] ]
```

CsvViewHandler.php

```
<?php

namespace Acme\MyBundle\View;

use FOS\RestBundle\View\View;
use FOS\RestBundle\View\ViewHandler;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class CsvViewHandler
{
    public function createResponse(ViewHandler $handler, View $view, Request $request, $format)
    {
        $csv = '<?xml version="1.0" encoding="ISO-8859-1"?>';
        $csv .= '<rss version="2.0">';
        $csv .= '<channel>';
        $csv .= '<title>My CSV</title>';
        $csv .= '<link>http://www.mywebsite.com</link>';
        $csv .= '<description>This is an example CSV</description>';
        $csv .= '<language>en-us</language>';
        $csv .= '<copyright>Copyright (C) 2009 mywebsite.com</copyright>';

        return new Response($csv, 200, $view->getHeaders());
    }
}
```

routing.yml

```
my_rest:
    type: rest
    resource: Acme\MyBundle\Controller\MyController
```

config.yml

```
...
fos_rest:
    routing_loader:
        default_format: html
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
#        formats:
#          csv: true  # thrown out an exception
#        templating_formats:
#          csv: false # give a blank view if it is true
...
```

Am I on a right track, or missing something? Can any one help me out? Thanks alot... :)

**Comment by jandom** [comment]
For completion of this thread, as per @lsmith77 you'd need to
```
fos_rest:
    # registering the mime type
    view:            
        mime_types: { 'csv': ['text/csv','text/plain'] }
        formats:
            json: true
            csv: true   
    # modifying the format listener
    format_listener:
        rules:
            # setting fallback_format to null, while setting exception_fallback_format to xml, will mean that in case of an exception, xml will be used
            - { path: '^/api', priorities: [ 'csv', 'json'], fallback_format: ~, exception_fallback_format: json    , prefer_extension: false }
```

References 
https://symfony.com/doc/current/bundles/FOSRestBundle/3-listener-support.html
https://symfony.com/doc/current/bundles/FOSRestBundle/format_listener.html
http://symfony.com/doc/current/cookbook/request/mime_type.html
