### ISSUE TITLE
No @QueryParam/@RequestParam configuration 

### ISSUE THREAD

**Issue by andrius-kulbis** [FriendsOfSymfony/FOSRestBundle#884]
My action in controller:

```
/*
 * @REST\QueryParam(name="page", requirements="\d+", default="1", description="page number")
 * @REST\QueryParam(name="pageSize", requirements="\d+", default="25", description="users per page")
 * @REST\View()
 */
public function allAction(ParamFetcher $paramFetcher) 
{
        $pageSize = $paramFetcher->get('pageSize');
        $page = $paramFetcher->get('page');

        $users = $this->get('backend.user.handler')->all($pageSize, $pageSize * $page - 1);

        return $users;
}
```

The config of FOSRestBundle:

```
fos_rest:
   param_fetcher_listener: true
   body_listener: true
   format_listener: false
   view:
        view_response_listener: 'force'
```

And the routing for this route:

```
backend_get_all_users:
    pattern:     /users
    defaults: { _controller: MyBackendBundle:User:all, _format: json }
    requirements:
        _method: GET
```

When I try to visit this route I get 

```
No @QueryParam/@RequestParam configuration for parameter 'pageSize'
```

What am I missing?
