### ISSUE TITLE
API version not added to Request attributes

### ISSUE THREAD

**Issue by amenophis** [FriendsOfSymfony/FOSRestBundle#894]
Hi
I have the following configuration:

``` yaml
fos_rest:
    disable_csrf_role: ROLE_CONTACT
    param_fetcher_listener: force
    format_listener:
        media_type:
            version_regex: '/(v|version)=(?P<version>[0-9\.]+)/'
        rules:
            - { path: '^/api', priorities: ['application/json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: false }
    view:
        mime_types:
            json:
                - application/vnd.my.app+json
                - application/vnd.my.app+json;version=1.0
                - application/vnd.my.app+json;version=2.0
        view_response_listener: force
        formats:
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
```

I call my api with the following Accept Header : `̀`application/vnd.my.app+json;version=1.0`̀`

I works well, the content is well served, but it seems the version attribute is not set as the mediaType here (https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/EventListener%2FVersionListener.php#L55) doesn't contains version anymore. Maybe stripped before ?

The Request attribute `media_type` contains `application/vnd.my.app+json` so the regex to extract the version could not work ...

@lsmith77 @willdurand what's wrong ?
