### ISSUE TITLE
[BUG] Update from 1.4.2 to 1.5.3 illegal offset type in GenericMetadata.php

### ISSUE THREAD

**Issue by entering** [FriendsOfSymfony/FOSRestBundle#973]
```
Warning: Illegal offset type in isset or empty in /vagrant/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/GenericMetadata.php line 216
500 Internal Server Error - ContextErrorException
```

symfony version: v2.5.3

The code:

```php
    /**
     * @QueryParam(
     *      name="letter",
     *      nullable=false,
     *      requirements="[A-Z\#]",
     *      default="A",
     *      strict=true,
     *      description="First letter of the Accommodation Provider's name to filter by"
     * )
     *
     * @param Request $request
     * @param string $letter
     *
     * @return Response
     */
    public function listAction(Request $request, $letter)
{
...
}
```

And the routing:
```yml
accommodation_provider_list:
    pattern:  /accommodation-providers
    defaults: { _controller: accommodation_bundle.accommodation_provider.controller:listAction }
    methods: [POST, GET]
```
