### ISSUE TITLE
Format listener with prefix instead of host

### ISSUE THREAD

**Issue by YoruNoHikage** [FriendsOfSymfony/FOSRestBundle#974]
Hello everyone,

I’m currently implementing this bundle and I would like my API and my website served in the same time but without becoming host specific.

 It’s actually working if I’m making the rules with the host parameter as specified in the docs but I have this :

```yaml
# app/config/config.yml
fos_rest:
    format_listener:
        rules:
            - { path: ‘^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: [‘html'], fallback_format: html, prefer_extension: false }
```

I would like /api served with JSON and / served with templates but **I have only one controller for both**. I can duplicate my routing files (and set name_prefix and prefix) but it’s breaking the route redirections set in my controllers. I would like to know your opinion on this. Do I have to specify a paramter to check if it’s the API or the website and changing my redirections according to this ? Is there any better way ? Or maybe it’s Symfony-related and I’m missing something.
If this is a missing feature, I can submit a pull request with your advices.

Thanks.
