### ISSUE TITLE
Delete method is not working

### ISSUE THREAD

**Issue by hyyan** [FriendsOfSymfony/FOSRestBundle#993]
Hey , thanks for the great work guys , it is impressive 

I am trying to build a simple task api just to learn , and everything is working great , except for the delete request , the form validation is passing in html  but it is not in json or xml and I keep getting the 400 code error (Bad Request)

I didn't post this in Stack Overflow cause I think it is a bug , 

`Note : I am using the master brunch `

Here's my bundle config ;

```yml
fos_rest:
    allowed_methods_listener: true
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml:  true
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - { path: ^/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
    allowed_methods_listener: true
    body_listener: true
    disable_csrf_role: ROLE_API
```

And here's my controller methods : 

```php

  /**
     * Creates a form to delete a Task entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder(null, array('csrf_protection' => false))
                        ->setAction($this->generateUrl('tasks_delete', array('id' => $id)))
                        ->setMethod('DELETE')
                        ->add('submit', 'submit', array('label' => 'Delete'))
                        ->getForm()
        ;
    }

  /**
     * Deletes a Task entity.
     *
     * @ApiDoc(
     *   resource = true,
     *   section= "Tasks",
     *   description = "Delete existing entity.",
     *   requirements={
     *      {
     *          "name"="id",
     *          "dataType"="integer",
     *          "requirement"="\d+",
     *          "description"="the task ID"
     *      }
     *   },
     *   statusCodes = {
     *     200 = "Returned when successful",
     *     404 = "Returned when entity does not exists",
     *     400 = "Returned when form can not be submitted",
     *   }
     * )
     */
    public function deleteAction(Request $request, $id)
    {

        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);
        
        $code = 400;
        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('AppBundle:Task')->getTaskById($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Task entity.');
            }

            $em->remove($entity);
            $em->flush();
            
            $code = 204;
        }

        $view = $this->routeRedirectView('tasks', array(), $code);
        return $this->handleView($view);
    }
```

And finally the route: 

```yml
tasks_delete:
    path:     /{id}
    defaults: { _controller: "AppBundle:Task:delete" , format: ~ }
    requirements: { _method: DELETE , id: \d+}
```

Any idea will be helpful , thanks in advance
